use serde_json::{json, Value};
use std::path::PathBuf;
use tauri::{AppHandle, Emitter};
use std::process::Stdio;
use tokio::io::AsyncBufReadExt;

pub async fn handle_project_scaffold(body: Value) -> Value {
    let path_str = body.get("path").and_then(|v| v.as_str()).unwrap_or_default();
    let template = body.get("template").and_then(|v| v.as_str()).unwrap_or_default();
    let options = body.get("options").cloned().unwrap_or_else(|| json!({}));
    
    if path_str.is_empty() {
      return json!({ "ok": false, "error": "[SCAFFOLD_FAILED] Missing path." });
    }
    
    let expanded = if path_str.starts_with("~/") {
      let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
      path_str.replacen("~/", &format!("{}/", home), 1)
    } else {
      path_str.to_string()
    };
    
    let project_dir = PathBuf::from(&expanded);
    if let Err(e) = std::fs::create_dir_all(&project_dir) {
      return json!({ "ok": false, "error": format!("[SCAFFOLD_FAILED] Could not create directory: {}", e) });
    }
    
    if template == "data-science" {
      // Create professional directories
      let _ = std::fs::create_dir_all(project_dir.join("data/raw"));
      let _ = std::fs::create_dir_all(project_dir.join("data/processed"));
      let _ = std::fs::create_dir_all(project_dir.join("notebooks"));
      let _ = std::fs::create_dir_all(project_dir.join("src"));
      let _ = std::fs::create_dir_all(project_dir.join("tests"));
      
      let _ = std::fs::write(project_dir.join("data/raw/.gitkeep"), "");
      let _ = std::fs::write(project_dir.join("data/processed/.gitkeep"), "");
      let _ = std::fs::write(project_dir.join("src/__init__.py"), "");
      
      // Generate .env
      let env_content = "DATABASE_URL=postgresql://postgres:luminadev@postgres:5432/datasci\n";
      let _ = std::fs::write(project_dir.join(".env"), env_content);
      
      // Generate .gitignore
      let gitignore = ".env\n__pycache__/\n*.pyc\ndata/raw/*\n!data/raw/.gitkeep\ndata/processed/*\n!data/processed/.gitkeep\n.ipynb_checkpoints/\n";
      let _ = std::fs::write(project_dir.join(".gitignore"), gitignore);
      
      // Generate README.md
      let readme = "# Data Science Project\n\nGenerated by LuminaDev.\n\n## Structure\n- `data/`: Raw and processed datasets.\n- `notebooks/`: Jupyter notebooks.\n- `src/`: Reusable Python modules.\n- `tests/`: Unit tests.\n".to_string();
      let _ = std::fs::write(project_dir.join("README.md"), readme);
      
      // Generate src/db.py
      let db_py = r#"import os
from sqlalchemy import create_engine

def get_engine():
    db_url = os.environ.get('DATABASE_URL')
    if not db_url:
        raise ValueError("DATABASE_URL environment variable is not set")
    return create_engine(db_url)
"#;
      let _ = std::fs::write(project_dir.join("src/db.py"), db_py);
      
      // Generate tests/test_db.py
      let test_db_py = r#"import unittest

class TestDatabase(unittest.TestCase):
    def test_connection_string(self):
        # Placeholder test
        self.assertTrue(True)

if __name__ == '__main__':
    unittest.main()
"#;
      let _ = std::fs::write(project_dir.join("tests/test_db.py"), test_db_py);
      
      // Generate src/data_loader.py
      let data_loader = r#"import pandas as pd
from .db import get_engine

def load_data_from_db(query: str) -> pd.DataFrame:
    engine = get_engine()
    return pd.read_sql(query, engine)
"#;
      let _ = std::fs::write(project_dir.join("src/data_loader.py"), data_loader);

      // Generate requirements.txt
      let deps = options.get("dependencies").and_then(|v| v.as_object()).cloned().unwrap_or_default();
      let mut reqs = String::new();
      for (name, version) in deps {
        let v_str = version.as_str().unwrap_or("latest").trim();
        if v_str.is_empty() || v_str == "latest" {
           reqs.push_str(&name);
        } else {
           reqs.push_str(&format!("{}=={}", name, v_str));
        }
        reqs.push('\n');
      }
      let _ = std::fs::write(project_dir.join("requirements.txt"), reqs);
      
      // Generate main.py
      let create_main = options.get("createMainScript").and_then(|v| v.as_bool()).unwrap_or(false);
      if create_main {
        let main_content = r#"from src.db import get_engine

def main():
    try:
        engine = get_engine()
        with engine.connect() as conn:
            print("Successfully connected to the database!")
    except Exception as e:
        print(f"Error connecting to database: {e}")

if __name__ == '__main__':
    main()
"#;
        let _ = std::fs::write(project_dir.join("main.py"), main_content);
      }
      
      // Generate exploration.ipynb
      let create_notebook = options.get("createNotebook").and_then(|v| v.as_bool()).unwrap_or(false);
      if create_notebook {
        let notebook_content = r##"{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data Exploration\n",
    "Welcome to your LuminaDev Data Science project."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.db import get_engine\n",
    "import pandas as pd\n",
    "\n",
    "engine = get_engine()\n",
    "print('Database connected!')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}"##;
        let _ = std::fs::write(project_dir.join("notebooks/01_exploration.ipynb"), notebook_content);
      }
    } else if template == "web-dev" {
      // Create professional directories
      let _ = std::fs::create_dir_all(project_dir.join("src/components"));
      let _ = std::fs::create_dir_all(project_dir.join("src/pages"));
      let _ = std::fs::create_dir_all(project_dir.join("public"));
      
      let _ = std::fs::write(project_dir.join("src/components/.gitkeep"), "");
      let _ = std::fs::write(project_dir.join("src/pages/.gitkeep"), "");
      let _ = std::fs::write(project_dir.join("public/.gitkeep"), "");
      
      // Generate .env
      let env_content = "DATABASE_URL=postgresql://postgres:luminadev@postgres:5432/webapp\n";
      let _ = std::fs::write(project_dir.join(".env"), env_content);
      
      // Generate .gitignore
      let gitignore = "node_modules\n.env\ndist\nbuild\n.DS_Store\n";
      let _ = std::fs::write(project_dir.join(".gitignore"), gitignore);
      
      // Generate README.md
      let readme = "# Web Development Project\n\nGenerated by LuminaDev.\n".to_string();
      let _ = std::fs::write(project_dir.join("README.md"), readme);
      
      let mut deps = options.get("dependencies").and_then(|v| v.as_object()).cloned().unwrap_or_default();
      deps.insert("react".to_string(), json!("^18.3.1"));
      deps.insert("react-dom".to_string(), json!("^18.3.1"));

      let mut dev_deps = options.get("devDependencies").and_then(|v| v.as_object()).cloned().unwrap_or_default();
      dev_deps.insert("vite".to_string(), json!("^5.4.1"));
      dev_deps.insert("typescript".to_string(), json!("^5.5.3"));
      dev_deps.insert("@vitejs/plugin-react".to_string(), json!("^4.3.1"));
      dev_deps.insert("@types/react".to_string(), json!("^18.3.3"));
      dev_deps.insert("@types/react-dom".to_string(), json!("^18.3.0"));
      
      // Generate package.json
      let package_json = serde_json::json!({
        "name": "lumina-web-app",
        "version": "1.0.0",
        "private": true,
        "scripts": {
           "dev": "vite",
           "build": "tsc && vite build",
           "preview": "vite preview"
        },
        "dependencies": deps,
        "devDependencies": dev_deps
      });
      
      let _ = std::fs::write(project_dir.join("package.json"), serde_json::to_string_pretty(&package_json).unwrap());
      
      // Generate a basic index.html and src/main.tsx
      let index_html = r#"<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LuminaDev Web App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>"#;
      let _ = std::fs::write(project_dir.join("index.html"), index_html);
      
      let main_tsx = r#"import React from 'react'
import ReactDOM from 'react-dom/client'

const App = () => {
  return (
    <div style={{ padding: 40, fontFamily: 'sans-serif' }}>
      <h1>Welcome to LuminaDev Web App!</h1>
      <p>This project was scaffolded with a professional Dockerized architecture.</p>
    </div>
  )
}

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
"#;
      let _ = std::fs::write(project_dir.join("src/main.tsx"), main_tsx);

      let vite_config = r#"import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    host: '0.0.0.0', // needed for Docker
    port: 5173
  }
})
"#;
      let _ = std::fs::write(project_dir.join("vite.config.ts"), vite_config);
    }
    
    json!({ "ok": true, "path": expanded })
}

pub async fn handle_project_install_deps(body: Value, app: AppHandle) -> Value {
    let project_name = body.get("projectName").and_then(|v| v.as_str()).unwrap_or_default();
    let template = body.get("template").and_then(|v| v.as_str()).unwrap_or("data-science");
    
    if project_name.is_empty() {
      return json!({ "ok": false, "error": "Missing projectName" });
    }
    
    let (container_name, work_dir, install_cmd, install_args) = if template == "web-dev" {
       (format!("{}-node-1", template), "/app", "npm", vec!["install"])
    } else {
       (format!("{}-jupyter-1", template), "/home/jovyan/work", "pip", vec!["install", "-r", "requirements.txt"])
    };
    
    let fut = async {
       let _ = app.emit("project-install-log", &format!("Waiting for container '{}' to start...", container_name));
       
       // Wait up to 10 seconds for the container to become responsive
       for _ in 0..10 {
          let out = tokio::process::Command::new("docker")
            .args(["exec", &container_name, "echo", "ready"])
            .output()
            .await
            .unwrap_or_else(|_| std::process::Output { status: std::os::unix::process::ExitStatusExt::from_raw(1), stdout: vec![], stderr: vec![] });
          if out.status.success() {
             let _ = app.emit("project-install-log", "Container is ready.");
             break;
          }
          tokio::time::sleep(std::time::Duration::from_millis(1000)).await;
       }
       
       let mut full_args = vec!["exec", "-w", work_dir, &container_name, install_cmd];
       full_args.extend(install_args);
       
       let _ = app.emit("project-install-log", &format!("Running '{}' inside container...", full_args.join(" ")));

       let mut child = tokio::process::Command::new("docker")
          .args(&full_args)
          .stdout(Stdio::piped())
          .stderr(Stdio::piped())
          .spawn()
          .map_err(|e| format!("[INSTALL_ERROR] {}", e))?;
          
       if let Some(stdout) = child.stdout.take() {
           let app_clone = app.clone();
           tokio::spawn(async move {
               let mut reader = tokio::io::BufReader::new(stdout).lines();
               while let Ok(Some(line)) = reader.next_line().await {
                   let _ = app_clone.emit("project-install-log", &line);
               }
           });
       }
       if let Some(stderr) = child.stderr.take() {
           let app_clone = app.clone();
           tokio::spawn(async move {
               let mut reader = tokio::io::BufReader::new(stderr).lines();
               while let Ok(Some(line)) = reader.next_line().await {
                   let _ = app_clone.emit("project-install-log", &line);
               }
           });
       }

       let status = child.wait().await.map_err(|e| format!("[INSTALL_ERROR] Wait failed: {}", e))?;
       if status.success() {
         Ok(("Dependencies installed successfully".to_string(), "".to_string()))
       } else {
         Err("Failed to install dependencies".to_string())
       }
    };
    
    match tokio::time::timeout(std::time::Duration::from_secs(120), fut).await {
       Ok(Ok((stdout, _))) => json!({ "ok": true, "log": stdout }),
       Ok(Err(e)) => json!({ "ok": false, "error": e }),
       Err(_) => json!({ "ok": false, "error": "Timeout installing dependencies" })
    }
}
