use serde_json::{json, Value};
use std::path::PathBuf;
use tauri::{AppHandle, Emitter};
use std::process::Stdio;
use tokio::io::AsyncBufReadExt;

pub async fn handle_project_scaffold(body: Value) -> Value {
    let path_str = body.get("path").and_then(|v| v.as_str()).unwrap_or_default();
    let template = body.get("template").and_then(|v| v.as_str()).unwrap_or_default();
    let options = body.get("options").cloned().unwrap_or_else(|| json!({}));
    
    if path_str.is_empty() {
      return json!({ "ok": false, "error": "[SCAFFOLD_FAILED] Missing path." });
    }
    
    let expanded = if path_str.starts_with("~/") {
      let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
      path_str.replacen("~/", &format!("{}/", home), 1)
    } else {
      path_str.to_string()
    };
    
    let project_dir = PathBuf::from(&expanded);
    if let Err(e) = std::fs::create_dir_all(&project_dir) {
      return json!({ "ok": false, "error": format!("[SCAFFOLD_FAILED] Could not create directory: {}", e) });
    }
    
    if template == "data-science" {
      // Create professional directories
      let _ = std::fs::create_dir_all(project_dir.join("data/raw"));
      let _ = std::fs::create_dir_all(project_dir.join("data/processed"));
      let _ = std::fs::create_dir_all(project_dir.join("notebooks"));
      let _ = std::fs::create_dir_all(project_dir.join("src"));
      let _ = std::fs::create_dir_all(project_dir.join("tests"));
      
      let _ = std::fs::write(project_dir.join("data/raw/.gitkeep"), "");
      let _ = std::fs::write(project_dir.join("data/processed/.gitkeep"), "");
      let _ = std::fs::write(project_dir.join("src/__init__.py"), "");
      
      // Generate .env
      let env_content = "DATABASE_URL=postgresql://postgres:luminadev@postgres:5432/datasci\n";
      let _ = std::fs::write(project_dir.join(".env"), env_content);
      
      // Generate .gitignore
      let gitignore = ".env\n__pycache__/\n*.pyc\ndata/raw/*\n!data/raw/.gitkeep\ndata/processed/*\n!data/processed/.gitkeep\n.ipynb_checkpoints/\n";
      let _ = std::fs::write(project_dir.join(".gitignore"), gitignore);
      
      // Generate README.md
      let readme = "# Data Science Project\n\nGenerated by LuminaDev.\n\n## Structure\n- `data/`: Raw and processed datasets.\n- `notebooks/`: Jupyter notebooks.\n- `src/`: Reusable Python modules.\n- `tests/`: Unit tests.\n".to_string();
      let _ = std::fs::write(project_dir.join("README.md"), readme);
      
      // Generate src/db.py
      let db_py = r#"import os
from sqlalchemy import create_engine

def get_engine():
    db_url = os.environ.get('DATABASE_URL')
    if not db_url:
        raise ValueError("DATABASE_URL environment variable is not set")
    return create_engine(db_url)
"#;
      let _ = std::fs::write(project_dir.join("src/db.py"), db_py);
      
      // Generate tests/test_db.py
      let test_db_py = r#"import unittest

class TestDatabase(unittest.TestCase):
    def test_connection_string(self):
        # Placeholder test
        self.assertTrue(True)

if __name__ == '__main__':
    unittest.main()
"#;
      let _ = std::fs::write(project_dir.join("tests/test_db.py"), test_db_py);
      
      // Generate src/data_loader.py
      let data_loader = r#"import pandas as pd
from .db import get_engine

def load_data_from_db(query: str) -> pd.DataFrame:
    engine = get_engine()
    return pd.read_sql(query, engine)
"#;
      let _ = std::fs::write(project_dir.join("src/data_loader.py"), data_loader);

      // Generate requirements.txt
      let deps = options.get("dependencies").and_then(|v| v.as_object()).cloned().unwrap_or_default();
      let mut reqs = String::new();
      for (name, version) in deps {
        let v_str = version.as_str().unwrap_or("latest").trim();
        if v_str.is_empty() || v_str == "latest" {
           reqs.push_str(&name);
        } else {
           reqs.push_str(&format!("{}=={}", name, v_str));
        }
        reqs.push('\n');
      }
      let _ = std::fs::write(project_dir.join("requirements.txt"), reqs);
      
      // Generate main.py
      let create_main = options.get("createMainScript").and_then(|v| v.as_bool()).unwrap_or(false);
      if create_main {
        let main_content = r#"from src.db import get_engine

def main():
    try:
        engine = get_engine()
        with engine.connect() as conn:
            print("Successfully connected to the database!")
    except Exception as e:
        print(f"Error connecting to database: {e}")

if __name__ == '__main__':
    main()
"#;
        let _ = std::fs::write(project_dir.join("main.py"), main_content);
      }
      
      // Generate exploration.ipynb
      let create_notebook = options.get("createNotebook").and_then(|v| v.as_bool()).unwrap_or(false);
      if create_notebook {
        let notebook_content = r##"{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data Exploration\n",
    "Welcome to your LuminaDev Data Science project."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.db import get_engine\n",
    "import pandas as pd\n",
    "\n",
    "engine = get_engine()\n",
    "print('Database connected!')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}"##;
        let _ = std::fs::write(project_dir.join("notebooks/01_exploration.ipynb"), notebook_content);
      }
      scaffold_editor_configs(&project_dir, "data-science", "");
    } else if template == "web-dev" {
      // Create professional directories
      let _ = std::fs::create_dir_all(project_dir.join("src/components"));
      let _ = std::fs::create_dir_all(project_dir.join("src/pages"));
      let _ = std::fs::create_dir_all(project_dir.join("public"));
      
      let _ = std::fs::write(project_dir.join("src/components/.gitkeep"), "");
      let _ = std::fs::write(project_dir.join("src/pages/.gitkeep"), "");
      let _ = std::fs::write(project_dir.join("public/.gitkeep"), "");
      
      // Generate .env
      let env_content = "DATABASE_URL=postgresql://postgres:luminadev@postgres:5432/webapp\n";
      let _ = std::fs::write(project_dir.join(".env"), env_content);
      
      // Generate .gitignore
      let gitignore = "node_modules\n.env\ndist\nbuild\n.DS_Store\n";
      let _ = std::fs::write(project_dir.join(".gitignore"), gitignore);
      
      // Generate README.md
      let readme = "# Web Development Project\n\nGenerated by LuminaDev.\n".to_string();
      let _ = std::fs::write(project_dir.join("README.md"), readme);
      
      let mut deps = options.get("dependencies").and_then(|v| v.as_object()).cloned().unwrap_or_default();
      deps.insert("react".to_string(), json!("^18.3.1"));
      deps.insert("react-dom".to_string(), json!("^18.3.1"));

      let mut dev_deps = options.get("devDependencies").and_then(|v| v.as_object()).cloned().unwrap_or_default();
      dev_deps.insert("vite".to_string(), json!("^5.4.1"));
      dev_deps.insert("typescript".to_string(), json!("^5.5.3"));
      dev_deps.insert("@vitejs/plugin-react".to_string(), json!("^4.3.1"));
      dev_deps.insert("@types/react".to_string(), json!("^18.3.3"));
      dev_deps.insert("@types/react-dom".to_string(), json!("^18.3.0"));
      
      // Generate package.json
      let package_json = serde_json::json!({
        "name": "lumina-web-app",
        "version": "1.0.0",
        "private": true,
        "scripts": {
           "dev": "vite",
           "build": "tsc && vite build",
           "preview": "vite preview"
        },
        "dependencies": deps,
        "devDependencies": dev_deps
      });
      
      let _ = std::fs::write(project_dir.join("package.json"), serde_json::to_string_pretty(&package_json).unwrap());
      
      // Generate a basic index.html and src/main.tsx
      let index_html = r#"<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LuminaDev Web App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>"#;
      let _ = std::fs::write(project_dir.join("index.html"), index_html);
      
      let main_tsx = r#"import React from 'react'
import ReactDOM from 'react-dom/client'

const App = () => {
  return (
    <div style={{ padding: 40, fontFamily: 'sans-serif' }}>
      <h1>Welcome to LuminaDev Web App!</h1>
      <p>This project was scaffolded with a professional Dockerized architecture.</p>
    </div>
  )
}

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
"#;
      let _ = std::fs::write(project_dir.join("src/main.tsx"), main_tsx);

      let vite_config = r#"import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    host: '0.0.0.0', // needed for Docker
    port: 5173
  }
})
"#;
      let _ = std::fs::write(project_dir.join("vite.config.ts"), vite_config);
      scaffold_editor_configs(&project_dir, "web-dev", "");
    }
    
    json!({ "ok": true, "path": expanded })
}

pub async fn handle_project_install_deps(body: Value, app: AppHandle) -> Value {
    let project_name = body.get("projectName").and_then(|v| v.as_str()).unwrap_or_default();
    let template = body.get("template").and_then(|v| v.as_str()).unwrap_or("data-science");
    
    if project_name.is_empty() {
      return json!({ "ok": false, "error": "Missing projectName" });
    }
    
    let profile_name_arg = body.get("profileName").and_then(|v| v.as_str()).unwrap_or("");
    let container_prefix = if !profile_name_arg.is_empty() {
        profile_name_arg.to_string()
    } else {
        let mut p_name = String::new();
        if let Ok(store_path) = crate::app_file(&app, "store.json") {
            let store = crate::read_json(&store_path);
            if let Some(act) = store.get("active_profile").and_then(|v| v.as_str()) {
                p_name = act.to_string();
            }
        }
        if p_name.is_empty() {
            template.to_string()
        } else {
            p_name
        }
    };

    let (container_name, work_dir, install_cmd, install_args) = if template == "web-dev" {
       (format!("{}-node-1", container_prefix), "/app", "npm", vec!["install"])
    } else {
       (format!("{}-jupyter-1", container_prefix), "/home/jovyan/work", "pip", vec!["install", "-r", "requirements.txt"])
    };
    
    let fut = async {
       let _ = app.emit("project-install-log", &format!("Waiting for container '{}' to start...", container_name));
       
       // Wait up to 10 seconds for the container to become responsive
       for _ in 0..10 {
          let out = tokio::process::Command::new("docker")
            .args(["exec", &container_name, "echo", "ready"])
            .output()
            .await
            .unwrap_or_else(|_| std::process::Output { status: std::os::unix::process::ExitStatusExt::from_raw(1), stdout: vec![], stderr: vec![] });
          if out.status.success() {
             let _ = app.emit("project-install-log", "Container is ready.");
             break;
          }
          tokio::time::sleep(std::time::Duration::from_millis(1000)).await;
       }
       
       let mut full_args = vec!["exec", "-w", work_dir, &container_name, install_cmd];
       full_args.extend(install_args);
       
       let _ = app.emit("project-install-log", &format!("Running '{}' inside container...", full_args.join(" ")));

       let mut child = tokio::process::Command::new("docker")
          .args(&full_args)
          .stdout(Stdio::piped())
          .stderr(Stdio::piped())
          .spawn()
          .map_err(|e| format!("[INSTALL_ERROR] {}", e))?;
          
       if let Some(stdout) = child.stdout.take() {
           let app_clone = app.clone();
           tokio::spawn(async move {
               let mut reader = tokio::io::BufReader::new(stdout).lines();
               while let Ok(Some(line)) = reader.next_line().await {
                   let _ = app_clone.emit("project-install-log", &line);
               }
           });
       }
       if let Some(stderr) = child.stderr.take() {
           let app_clone = app.clone();
           tokio::spawn(async move {
               let mut reader = tokio::io::BufReader::new(stderr).lines();
               while let Ok(Some(line)) = reader.next_line().await {
                   let _ = app_clone.emit("project-install-log", &line);
               }
           });
       }

       let status = child.wait().await.map_err(|e| format!("[INSTALL_ERROR] Wait failed: {}", e))?;
       if status.success() {
         Ok(("Dependencies installed successfully".to_string(), "".to_string()))
       } else {
         Err("Failed to install dependencies".to_string())
       }
    };
    
        match tokio::time::timeout(std::time::Duration::from_secs(120), fut).await {
        Ok(Ok((stdout, _))) => json!({ "ok": true, "log": stdout }),
        Ok(Err(e)) => json!({ "ok": false, "error": e }),
        Err(_) => json!({ "ok": false, "error": "Timeout installing dependencies" })
     }
}

pub fn scaffold_mobile_react_native(
    project_dir: &std::path::Path,
    env_vars: &[(&str, &str)],
) -> Result<(), String> {
    let w = |path: &str, content: &str| {
        std::fs::write(project_dir.join(path), content)
            .map_err(|e| format!("[SCAFFOLD_FAILED] write {path}: {e}"))
    };
    std::fs::create_dir_all(project_dir.join("android"))
        .map_err(|e| format!("[SCAFFOLD_FAILED] mkdir android: {e}"))?;
    std::fs::create_dir_all(project_dir.join("ios"))
        .map_err(|e| format!("[SCAFFOLD_FAILED] mkdir ios: {e}"))?;

    let package_json = serde_json::json!({
        "name": "lumina-mobile-app",
        "version": "0.0.1",
        "private": true,
        "scripts": {
            "android": "react-native run-android",
            "ios": "react-native run-ios",
            "start": "react-native start",
            "test": "jest"
        },
        "dependencies": {
            "react": "18.2.0",
            "react-native": "0.74.0",
            "@react-navigation/native": "^6.1.0",
            "@react-navigation/stack": "^6.3.0"
        },
        "devDependencies": {
            "@babel/core": "^7.20.0",
            "@babel/preset-env": "^7.20.0",
            "@babel/runtime": "^7.20.0",
            "@react-native/metro-config": "^0.74.0",
            "@types/react": "^18.0.24",
            "@types/react-native": "^0.72.0",
            "jest": "^29.0.0",
            "typescript": "5.0.4"
        },
        "jest": {
            "preset": "react-native"
        }
    });
    w("package.json", &serde_json::to_string_pretty(&package_json).unwrap())?;

    w("metro.config.js", r#"const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const config = {};
module.exports = mergeConfig(getDefaultConfig(__dirname), config);
"#)?;

    w("index.js", r#"import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './package.json';
AppRegistry.registerComponent(appName, () => App);
"#)?;

    w("App.tsx", r#"import React from 'react';
import {SafeAreaView, Text, StyleSheet} from 'react-native';

export default function App(): React.JSX.Element {
  return (
    <SafeAreaView style={styles.container}>
      <Text style={styles.title}>LuminaDev Mobile App</Text>
      <Text style={styles.subtitle}>Edit App.tsx to get started.</Text>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#1a1a2e'},
  title: {fontSize: 24, fontWeight: 'bold', color: '#e0e0ff'},
  subtitle: {fontSize: 14, color: '#9090aa', marginTop: 8},
});
"#)?;

    let mut env_content = String::new();
    for (k, v) in env_vars {
        env_content.push_str(&format!("{k}={v}\n"));
    }
    w(".env", &env_content)?;

    w(".gitignore", "node_modules/\n.env\nbuild/\nandroid/app/build/\nios/build/\n*.jks\n*.keystore\n")?;

    w("docker-compose.yml", r#"services:
  appium:
    image: appium/appium:latest
    ports:
      - "4723:4723"
    environment:
      - ANDROID_SDK_ROOT=/opt/android-sdk
  json-server:
    image: clue/json-server
    ports:
      - "3001:80"
    volumes:
      - ./mock-data.json:/data/db.json
"#)?;

    w("mock-data.json", r#"{"users": [], "posts": []}
"#)?;

    w("tsconfig.json", r#"{
  "extends": "@react-native/typescript-config/tsconfig.json"
}
"#)?;

    Ok(())
}

pub fn detect_template(project_dir: &std::path::Path) -> String {
    if project_dir.join("package.json").exists() {
        "web-dev".to_string()
    } else {
        "data-science".to_string()
    }
}

pub fn scaffold_editor_configs(project_dir: &std::path::Path, template: &str, editor_cmd: &str) {
    // 1. VS Code / Cursor: Always write/ensure .vscode/extensions.json
    let vscode_dir = project_dir.join(".vscode");
    let _ = std::fs::create_dir_all(&vscode_dir);
    let vscode_content = if template == "data-science" {
        r#"{
  "recommendations": [
    "ms-python.python",
    "ms-toolsai.jupyter"
  ]
}"#
    } else {
        r#"{
  "recommendations": [
    "dbaeumer.vscode-eslint",
    "esbenp.prettier-vscode",
    "ms-vscode.vscode-typescript-next"
  ]
}"#
    };
    let _ = std::fs::write(vscode_dir.join("extensions.json"), vscode_content);

    // 2. IntelliJ IDEA: If the editor cmd is idea or webstorm or eclipse
    if editor_cmd.contains("idea") || editor_cmd.contains("webstorm") || editor_cmd.contains("eclipse") {
        let idea_dir = project_dir.join(".idea");
        let _ = std::fs::create_dir_all(&idea_dir);
        
        let modules_content = r#"<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ProjectModuleManager">
    <modules>
      <module fileurl="file://$PROJECT_DIR$/.idea/project.iml" filepath="$PROJECT_DIR$/.idea/project.iml" />
    </modules>
  </component>
</project>"#;
        let _ = std::fs::write(idea_dir.join("modules.xml"), modules_content);

        let iml_content = if template == "data-science" {
            r#"<?xml version="1.0" encoding="UTF-8"?>
<module type="PYTHON_MODULE" version="4">
  <component name="NewModuleRootManager">
    <content url="file://$MODULE_DIR$/.." />
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>"#
        } else {
            r#"<?xml version="1.0" encoding="UTF-8"?>
<module type="WEB_MODULE" version="4">
  <component name="NewModuleRootManager">
    <content url="file://$MODULE_DIR$/.." />
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>"#
        };
        let _ = std::fs::write(idea_dir.join("project.iml"), iml_content);

        if template == "data-science" {
            let misc_content = r#"<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ProjectRootManager" version="2" project-jdk-name="Python 3" project-jdk-type="Python SDK" />
</project>"#;
            let _ = std::fs::write(idea_dir.join("misc.xml"), misc_content);
        }
    }

    // 3. Neovim / Pyright
    if template == "data-science" {
        let pyright_content = r#"{
  "include": ["src", "tests", "main.py"],
  "exclude": ["**/node_modules", "**/__pycache__"]
}"#;
        let _ = std::fs::write(project_dir.join("pyrightconfig.json"), pyright_content);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_scaffold_editor_configs_vscode_data_science() {
        let base_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("test_scaffold_vscode_ds");
        let _ = std::fs::remove_dir_all(&base_dir);
        let _ = std::fs::create_dir_all(&base_dir);

        scaffold_editor_configs(&base_dir, "data-science", "code");

        let ext_file = base_dir.join(".vscode").join("extensions.json");
        assert!(ext_file.exists());

        let content = std::fs::read_to_string(ext_file).unwrap();
        assert!(content.contains("ms-python.python"));
        assert!(content.contains("ms-toolsai.jupyter"));

        let pyright_file = base_dir.join("pyrightconfig.json");
        assert!(pyright_file.exists());

        let _ = std::fs::remove_dir_all(&base_dir);
    }

    #[test]
    fn test_scaffold_editor_configs_intellij_web_dev() {
        let base_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("test_scaffold_idea_web");
        let _ = std::fs::remove_dir_all(&base_dir);
        let _ = std::fs::create_dir_all(&base_dir);

        scaffold_editor_configs(&base_dir, "web-dev", "idea");

        let ext_file = base_dir.join(".vscode").join("extensions.json");
        assert!(ext_file.exists());

        let content = std::fs::read_to_string(ext_file).unwrap();
        assert!(content.contains("esbenp.prettier-vscode"));

        let idea_modules = base_dir.join(".idea").join("modules.xml");
        let idea_iml = base_dir.join(".idea").join("project.iml");
        assert!(idea_modules.exists());
        assert!(idea_iml.exists());

        let iml_content = std::fs::read_to_string(idea_iml).unwrap();
        assert!(iml_content.contains("WEB_MODULE"));

        let _ = std::fs::remove_dir_all(&base_dir);
    }

    #[test]
    fn scaffold_rn_creates_expected_files() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_mobile_react_native(dir.path(), &[]).unwrap();
        assert!(dir.path().join("package.json").exists());
        assert!(dir.path().join("metro.config.js").exists());
        assert!(dir.path().join("index.js").exists());
        assert!(dir.path().join("App.tsx").exists());
        assert!(dir.path().join(".env").exists());
        assert!(dir.path().join(".gitignore").exists());
        assert!(dir.path().join("android").is_dir());
        assert!(dir.path().join("ios").is_dir());
    }

    #[test]
    fn test_detect_template() {
        let base_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("test_detect_template");
        let _ = std::fs::remove_dir_all(&base_dir);
        let _ = std::fs::create_dir_all(&base_dir);

        assert_eq!(detect_template(&base_dir), "data-science");

        let _ = std::fs::write(base_dir.join("package.json"), "{}");
        assert_eq!(detect_template(&base_dir), "web-dev");

        let _ = std::fs::remove_dir_all(&base_dir);
    }
}
