use serde_json::{json, Value};
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::Arc;
use tauri::{AppHandle, Emitter};
use tokio::io::AsyncBufReadExt;
use tokio::sync::Mutex;

use crate::utils::sanitize_compose_project_name;

const CRAN_MIRROR: &str = "https://cloud.r-project.org";

fn sanitize_r_package_name(name: &str) -> Option<String> {
    let t = name.trim();
    if t.is_empty()
        || !t
            .chars()
            .all(|c| c.is_alphanumeric() || c == '.' || c == '_')
    {
        return None;
    }
    Some(t.to_string())
}

/// Non-interactive install script for Docker (CRAN mirror required).
pub(crate) fn render_install_r_script(package_names: &[String]) -> String {
    let mut pkgs: Vec<String> = package_names
        .iter()
        .filter_map(|n| sanitize_r_package_name(n))
        .collect();
    if pkgs.is_empty() {
        pkgs.push("ggplot2".to_string());
    }
    let list = pkgs
        .iter()
        .map(|p| format!("\"{}\"", p))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "options(repos = c(CRAN = \"{CRAN_MIRROR}\"))\n\npkgs <- c({list})\ninstall.packages(pkgs, repos = getOption(\"repos\"), dependencies = TRUE)\n"
    )
}

fn find_free_port(preferred: u16) -> u16 {
    for port in preferred..preferred.saturating_add(200) {
        if std::net::TcpListener::bind(("127.0.0.1", port)).is_ok() {
            return port;
        }
    }
    preferred
}

pub async fn handle_project_scaffold(body: Value) -> Value {
    let path_str = body
        .get("path")
        .and_then(|v| v.as_str())
        .unwrap_or_default();
    let template = body
        .get("template")
        .and_then(|v| v.as_str())
        .unwrap_or_default();
    let options = body.get("options").cloned().unwrap_or_else(|| json!({}));

    if path_str.is_empty() {
        return json!({ "ok": false, "error": "[SCAFFOLD_FAILED] Missing path." });
    }

    let expanded = if path_str.starts_with("~/") {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
        path_str.replacen("~/", &format!("{}/", home), 1)
    } else {
        path_str.to_string()
    };

    let project_dir = PathBuf::from(&expanded);
    if let Err(e) = std::fs::create_dir_all(&project_dir) {
        return json!({ "ok": false, "error": format!("[SCAFFOLD_FAILED] Could not create directory: {}", e) });
    }

    if template == "data-science" {
        let toolchain = options
            .get("toolchain")
            .and_then(|v| v.as_str())
            .unwrap_or("python");
        let create_python = toolchain == "python" || toolchain == "both";
        let create_r = toolchain == "r" || toolchain == "both";

        // Create professional directories
        let _ = std::fs::create_dir_all(project_dir.join("data/raw"));
        let _ = std::fs::create_dir_all(project_dir.join("data/processed"));
        let _ = std::fs::create_dir_all(project_dir.join("notebooks"));
        let _ = std::fs::create_dir_all(project_dir.join("src"));
        let _ = std::fs::create_dir_all(project_dir.join("tests"));

        let _ = std::fs::write(project_dir.join("data/raw/.gitkeep"), "");
        let _ = std::fs::write(project_dir.join("data/processed/.gitkeep"), "");
        if create_python {
            let _ = std::fs::write(project_dir.join("src/__init__.py"), "");
        }

        // Generate .env
        let env_content = "DATABASE_URL=postgresql://postgres:luminadev@postgres:5432/datasci\n";
        let _ = std::fs::write(project_dir.join(".env"), env_content);

        // Generate .gitignore
        let mut gitignore = String::from(".env\ndata/raw/*\n!data/raw/.gitkeep\ndata/processed/*\n!data/processed/.gitkeep\n.ipynb_checkpoints/\n");
        if create_python {
            gitignore.push_str("__pycache__/\n*.pyc\n");
        }
        if create_r {
            gitignore.push_str(".Rhistory\n.RData\n.Ruserdata\n");
        }
        let _ = std::fs::write(project_dir.join(".gitignore"), gitignore);

        // Generate README.md
        let readme = "# Data Science Project\n\nGenerated by LuminaDev.\n\n## Structure\n- `data/`: Raw and processed datasets.\n- `notebooks/`: Jupyter notebooks.\n- `src/`: Reusable modules.\n- `tests/`: Unit tests.\n".to_string();
        let _ = std::fs::write(project_dir.join("README.md"), readme);

        if create_python {
            // Generate src/db.py
            let db_py = r#"import os
from sqlalchemy import create_engine

def get_engine():
    db_url = os.environ.get('DATABASE_URL')
    if not db_url:
        raise ValueError("DATABASE_URL environment variable is not set")
    return create_engine(db_url)
"#;
            let _ = std::fs::write(project_dir.join("src/db.py"), db_py);

            // Generate tests/test_db.py
            let test_db_py = r#"import unittest

class TestDatabase(unittest.TestCase):
    def test_connection_string(self):
        # Placeholder test
        self.assertTrue(True)

if __name__ == '__main__':
    unittest.main()
"#;
            let _ = std::fs::write(project_dir.join("tests/test_db.py"), test_db_py);

            // Generate src/data_loader.py
            let data_loader = r#"import pandas as pd
from .db import get_engine

def load_data_from_db(query: str) -> pd.DataFrame:
    engine = get_engine()
    return pd.read_sql(query, engine)
"#;
            let _ = std::fs::write(project_dir.join("src/data_loader.py"), data_loader);

            // Generate requirements.txt (Python packages only when toolchain is "both")
            let deps = options
                .get("dependencies")
                .and_then(|v| v.as_object())
                .filter(|o| !o.is_empty())
                .cloned()
                .unwrap_or_default();
            let mut reqs = String::new();
            for (name, version) in deps.iter() {
                let v_str = version.as_str().unwrap_or("latest").trim();
                if v_str.is_empty() || v_str == "latest" {
                    reqs.push_str(name);
                } else {
                    reqs.push_str(&format!("{}=={}", name, v_str));
                }
                reqs.push('\n');
            }
            let _ = std::fs::write(project_dir.join("requirements.txt"), reqs);
        }

        if create_r {
            let db_r = r#"library(DBI)
library(RPostgres)

get_engine <- function() {
  db_url <- Sys.getenv("DATABASE_URL")
  if (db_url == "") stop("DATABASE_URL environment variable is not set")

  # Placeholder connection logic
  # dbConnect(RPostgres::Postgres(), ...)
}
"#;
            let _ = std::fs::write(project_dir.join("src/db.R"), db_r);

            let data_loader_r = r#"source("src/db.R")

load_data_from_db <- function(query) {
  # Placeholder
}
"#;
            let _ = std::fs::write(project_dir.join("src/data_loader.R"), data_loader_r);

            // Generate install.R (rDependencies when set; else dependencies for R-only projects)
            let deps = options
                .get("rDependencies")
                .and_then(|v| v.as_object())
                .filter(|o| !o.is_empty())
                .cloned()
                .or_else(|| {
                    options
                        .get("dependencies")
                        .and_then(|v| v.as_object())
                        .cloned()
                })
                .unwrap_or_default();
            let r_names: Vec<String> = deps.keys().map(|k| k.to_string()).collect();
            let _ = std::fs::write(project_dir.join("install.R"), render_install_r_script(&r_names));
        }

        let create_main = options
            .get("createMainScript")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        if create_main {
            if create_python {
                let main_content = r#"from src.db import get_engine

def main():
    try:
        engine = get_engine()
        with engine.connect() as conn:
            print("Successfully connected to the database!")
    except Exception as e:
        print(f"Error connecting to database: {e}")

if __name__ == '__main__':
    main()
"#;
                let _ = std::fs::write(project_dir.join("main.py"), main_content);
            }

            if create_r {
                let main_r = r#"source("src/db.R")

main <- function() {
  tryCatch({
    con <- get_engine()
    print("Successfully connected to the database!")
  }, error = function(e) {
    print(paste("Error connecting to database:", e$message))
  })
}

if (!interactive()) {
  main()
}
"#;
                let _ = std::fs::write(project_dir.join("main.R"), main_r);
            }
        }

        let create_notebook = options
            .get("createNotebook")
            .and_then(|v| v.as_bool())
            .unwrap_or(false);
        if create_notebook {
            if create_python {
                let notebook_content = r##"{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data Exploration\n",
    "Welcome to your LuminaDev Data Science project."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.db import get_engine\n",
    "import pandas as pd\n",
    "\n",
    "engine = get_engine()\n",
    "print('Database connected!')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}"##;
                let _ = std::fs::write(
                    project_dir.join("notebooks/01_exploration.ipynb"),
                    notebook_content,
                );
            }

            if create_r {
                let notebook_r = r##"{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# R Data Exploration\n",
    "Welcome to your LuminaDev Data Science project (R)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "source('src/db.R')\n",
    "print('Database connected!')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}"##;
                let name = if create_python {
                    "notebooks/02_exploration_r.ipynb"
                } else {
                    "notebooks/01_exploration.ipynb"
                };
                let _ = std::fs::write(project_dir.join(name), notebook_r);
            }
        }
        scaffold_editor_configs(&project_dir, "data-science", "");
        if create_r {
            let extensions_json = r#"{
  "recommendations": [
    "ms-python.python",
    "ms-toolsai.jupyter",
    "reditorsupport.r"
  ]
}"#;
            let _ = std::fs::write(project_dir.join(".vscode/extensions.json"), extensions_json);
        }
    } else if template == "web-dev" {
        // Create professional directories
        let _ = std::fs::create_dir_all(project_dir.join("src/components"));
        let _ = std::fs::create_dir_all(project_dir.join("src/pages"));
        let _ = std::fs::create_dir_all(project_dir.join("public"));

        let _ = std::fs::write(project_dir.join("src/components/.gitkeep"), "");
        let _ = std::fs::write(project_dir.join("src/pages/.gitkeep"), "");
        let _ = std::fs::write(project_dir.join("public/.gitkeep"), "");

        // Generate .env
        let env_content = "DATABASE_URL=postgresql://postgres:luminadev@postgres:5432/webapp\n";
        let _ = std::fs::write(project_dir.join(".env"), env_content);

        // Generate .gitignore
        let gitignore = "node_modules\n.env\ndist\nbuild\n.DS_Store\n";
        let _ = std::fs::write(project_dir.join(".gitignore"), gitignore);

        // Generate README.md
        let readme = "# Web Development Project\n\nGenerated by LuminaDev.\n".to_string();
        let _ = std::fs::write(project_dir.join("README.md"), readme);

        let mut deps = options
            .get("dependencies")
            .and_then(|v| v.as_object())
            .cloned()
            .unwrap_or_default();
        deps.insert("react".to_string(), json!("^18.3.1"));
        deps.insert("react-dom".to_string(), json!("^18.3.1"));

        let mut dev_deps = options
            .get("devDependencies")
            .and_then(|v| v.as_object())
            .cloned()
            .unwrap_or_default();
        dev_deps.insert("vite".to_string(), json!("^5.4.1"));
        dev_deps.insert("typescript".to_string(), json!("^5.5.3"));
        dev_deps.insert("@vitejs/plugin-react".to_string(), json!("^4.3.1"));
        dev_deps.insert("@types/react".to_string(), json!("^18.3.3"));
        dev_deps.insert("@types/react-dom".to_string(), json!("^18.3.0"));

        // Generate package.json
        let package_json = serde_json::json!({
          "name": "lumina-web-app",
          "version": "1.0.0",
          "private": true,
          "scripts": {
             "dev": "vite",
             "build": "tsc && vite build",
             "preview": "vite preview"
          },
          "dependencies": deps,
          "devDependencies": dev_deps
        });

        let _ = std::fs::write(
            project_dir.join("package.json"),
            serde_json::to_string_pretty(&package_json).unwrap(),
        );

        // Generate a basic index.html and src/main.tsx
        let index_html = r#"<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LuminaDev Web App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>"#;
        let _ = std::fs::write(project_dir.join("index.html"), index_html);

        let main_tsx = r#"import React from 'react'
import ReactDOM from 'react-dom/client'

const App = () => {
  return (
    <div style={{ padding: 40, fontFamily: 'sans-serif' }}>
      <h1>Welcome to LuminaDev Web App!</h1>
      <p>This project was scaffolded with a professional Dockerized architecture.</p>
    </div>
  )
}

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
"#;
        let _ = std::fs::write(project_dir.join("src/main.tsx"), main_tsx);

        let vite_config = r#"import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    host: '0.0.0.0', // needed for Docker
    port: 5173
  }
})
"#;
        let _ = std::fs::write(project_dir.join("vite.config.ts"), vite_config);
        scaffold_editor_configs(&project_dir, "web-dev", "");
    } else if template == "mobile" {
        let sub = body
            .get("subTemplate")
            .and_then(|v| v.as_str())
            .unwrap_or("react-native");
        let env_pairs: Vec<(&str, &str)> = vec![];
        let result = if sub == "flutter" {
            scaffold_mobile_flutter(&project_dir, &env_pairs)
        } else {
            scaffold_mobile_react_native(&project_dir, &env_pairs)
        };
        if let Err(e) = result {
            return json!({ "ok": false, "error": e });
        }
    } else if template == "ai-ml" {
        let env_pairs: Vec<(&str, &str)> = vec![];
        if let Err(e) = scaffold_ai_ml(&project_dir, &env_pairs) {
            return json!({ "ok": false, "error": e });
        }
    } else if template == "docs" {
        if let Err(e) = scaffold_docs(&project_dir) {
            return json!({ "ok": false, "error": e });
        }
    }

    json!({ "ok": true, "path": expanded })
}

pub(crate) fn expand_tilde_path(path_str: &str) -> String {
    if path_str.starts_with("~/") {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
        path_str.replacen("~/", &format!("{}/", home), 1)
    } else {
        path_str.to_string()
    }
}

pub(crate) struct DepsInstallPlan {
    pub container_name: String,
    pub work_dir: &'static str,
    pub run_pip: bool,
    pub run_r: bool,
}

pub(crate) fn deps_install_plan(
    template: &str,
    toolchain: &str,
    profile_name: &str,
    project_dir: &Path,
) -> Result<DepsInstallPlan, String> {
    let compose_project = sanitize_compose_project_name(profile_name);
    if compose_project.is_empty() {
        return Err("[INSTALL_ERROR] Missing profile name for container lookup.".to_string());
    }

    let (service, work_dir, default_pip) = if template == "web-dev" {
        ("node", "/app", true)
    } else {
        ("jupyter", "/home/jovyan/work", false)
    };

    let has_requirements = project_dir.join("requirements.txt").is_file();
    let has_install_r = project_dir.join("install.R").is_file();

    let run_pip = if template == "web-dev" {
        true
    } else {
        matches!(toolchain, "python" | "both") && has_requirements
    };
    let run_r = has_install_r && matches!(toolchain, "r" | "both");

    if !run_pip && !run_r {
        if default_pip && template != "web-dev" && matches!(toolchain, "python" | "both") {
            return Err(
                "[INSTALL_ERROR] requirements.txt not found — recreate the project or add the file."
                    .to_string(),
            );
        }
        return Ok(DepsInstallPlan {
            container_name: format!("{compose_project}-{service}-1"),
            work_dir,
            run_pip: false,
            run_r: false,
        });
    }

    Ok(DepsInstallPlan {
        container_name: format!("{compose_project}-{service}-1"),
        work_dir,
        run_pip,
        run_r,
    })
}

async fn container_path_exists(container_name: &str, path: &str) -> bool {
    tokio::process::Command::new("docker")
        .args(["exec", container_name, "test", "-e", path])
        .output()
        .await
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// FULL compose overlay used a named volume and hid host projects — copy scaffold files in when needed.
async fn sync_project_into_container(
    app: &AppHandle,
    container_name: &str,
    work_dir: &str,
    project_dir: &Path,
) -> Result<(), String> {
    let work = work_dir.trim_end_matches('/');
    let needs_req = project_dir.join("requirements.txt").is_file();
    let needs_r = project_dir.join("install.R").is_file();
    if !needs_req && !needs_r {
        return Ok(());
    }
    let req_in_container = if needs_req {
        container_path_exists(container_name, &format!("{work}/requirements.txt")).await
    } else {
        true
    };
    let r_in_container = if needs_r {
        container_path_exists(container_name, &format!("{work}/install.R")).await
    } else {
        true
    };
    if req_in_container && r_in_container {
        return Ok(());
    }

    let _ = app.emit(
        "project-install-log",
        "Copying project files into the workspace container...",
    );
    let src = format!("{}/.", project_dir.display());
    let dest = format!("{container_name}:{work}/.");
    let output = tokio::process::Command::new("docker")
        .args(["cp", &src, &dest])
        .output()
        .await
        .map_err(|e| format!("[INSTALL_ERROR] docker cp: {}", e))?;
    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!(
            "[INSTALL_ERROR] Could not copy project into container. {}",
            stderr.trim()
        ));
    }
    Ok(())
}

async fn push_install_log_line(tail: &Mutex<Vec<String>>, line: &str) {
    let t = line.trim();
    if t.is_empty() {
        return;
    }
    let mut guard = tail.lock().await;
    if guard.len() >= 24 {
        guard.remove(0);
    }
    guard.push(t.to_string());
}

async fn run_docker_exec_logged(app: &AppHandle, args: &[&str]) -> Result<(), String> {
    let mut child = tokio::process::Command::new("docker")
        .args(args)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("[INSTALL_ERROR] {}", e))?;

    let log_tail = Arc::new(Mutex::new(Vec::<String>::new()));

    if let Some(stdout) = child.stdout.take() {
        let app_clone = app.clone();
        let tail = log_tail.clone();
        tokio::spawn(async move {
            let mut reader = tokio::io::BufReader::new(stdout).lines();
            while let Ok(Some(line)) = reader.next_line().await {
                push_install_log_line(&tail, &line).await;
                let _ = app_clone.emit("project-install-log", &line);
            }
        });
    }
    if let Some(stderr) = child.stderr.take() {
        let app_clone = app.clone();
        let tail = log_tail.clone();
        tokio::spawn(async move {
            let mut reader = tokio::io::BufReader::new(stderr).lines();
            while let Ok(Some(line)) = reader.next_line().await {
                push_install_log_line(&tail, &line).await;
                let _ = app_clone.emit("project-install-log", &line);
            }
        });
    }

    let status = child
        .wait()
        .await
        .map_err(|e| format!("[INSTALL_ERROR] Wait failed: {}", e))?;
    tokio::time::sleep(std::time::Duration::from_millis(200)).await;

    if status.success() {
        Ok(())
    } else {
        let guard = log_tail.lock().await;
        let hint: String = guard
            .iter()
            .rev()
            .take(6)
            .collect::<Vec<_>>()
            .into_iter()
            .rev()
            .map(|s| s.as_str())
            .collect::<Vec<_>>()
            .join(" | ");
        let detail = if hint.is_empty() {
            "Check Docker logs.".to_string()
        } else {
            hint
        };
        Err(format!(
            "[INSTALL_ERROR] Package install failed inside the container. {}",
            detail
        ))
    }
}

pub async fn handle_project_install_deps(body: Value, app: AppHandle) -> Value {
    let project_name = body
        .get("projectName")
        .and_then(|v| v.as_str())
        .unwrap_or_default();
    let template = body
        .get("template")
        .and_then(|v| v.as_str())
        .unwrap_or("data-science");

    if project_name.is_empty() {
        return json!({ "ok": false, "error": "Missing projectName" });
    }

    let profile_name_arg = body
        .get("profileName")
        .and_then(|v| v.as_str())
        .unwrap_or("");
    let profile_name = if !profile_name_arg.is_empty() {
        profile_name_arg.to_string()
    } else {
        let mut p_name = String::new();
        if let Ok(store_path) = crate::app_file(&app, "store.json") {
            let store = crate::read_json(&store_path);
            if let Some(act) = store.get("active_profile").and_then(|v| v.as_str()) {
                p_name = act.to_string();
            }
        }
        if p_name.is_empty() {
            template.to_string()
        } else {
            p_name
        }
    };

    let toolchain = body
        .get("toolchain")
        .and_then(|v| v.as_str())
        .unwrap_or("python");

    let project_dir = if let Some(path) = body.get("projectPath").and_then(|v| v.as_str()) {
        PathBuf::from(expand_tilde_path(path))
    } else {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/root".to_string());
        let mut base = PathBuf::from(home).join("LuminaProjects");
        if let Ok(store_path) = crate::app_file(&app, "store.json") {
            let store = crate::read_json(&store_path);
            if let Some(dir) = store.get("projects_home_dir").and_then(|v| v.as_str()) {
                base = PathBuf::from(expand_tilde_path(dir));
            }
        }
        base.join(&profile_name).join(project_name)
    };

    let plan = match deps_install_plan(template, toolchain, &profile_name, &project_dir) {
        Ok(p) => p,
        Err(e) => return json!({ "ok": false, "error": e }),
    };

    if !plan.run_pip && !plan.run_r {
        return json!({
            "ok": true,
            "log": "No dependency install step required for this project."
        });
    }

    let container_name = plan.container_name;
    let work_dir = plan.work_dir;
    let run_pip = plan.run_pip;
    let run_r = plan.run_r;

    let fut = async {
        let _ = app.emit(
            "project-install-log",
            &format!("Waiting for container '{}' to start...", container_name),
        );

        // Wait up to ~2 minutes for the container to become responsive
        let mut container_ready = false;
        for _ in 0..60 {
            let out = tokio::process::Command::new("docker")
                .args(["exec", &container_name, "echo", "ready"])
                .output()
                .await
                .unwrap_or_else(|_| std::process::Output {
                    status: std::os::unix::process::ExitStatusExt::from_raw(1),
                    stdout: vec![],
                    stderr: vec![],
                });
            if out.status.success() {
                container_ready = true;
                let _ = app.emit("project-install-log", "Container is ready.");
                break;
            }
            tokio::time::sleep(std::time::Duration::from_millis(2000)).await;
        }
        if !container_ready {
            return Err(format!(
                "[INSTALL_ERROR] Container '{}' is not running. Start the profile stack first, then retry.",
                container_name
            ));
        }

        sync_project_into_container(&app, &container_name, work_dir, &project_dir).await?;

        if run_pip {
            let pip_cmd = if template == "web-dev" {
                "npm install"
            } else {
                "python -m pip install -r requirements.txt"
            };
            let _ = app.emit(
                "project-install-log",
                &format!("Running {pip_cmd} inside container..."),
            );
            let pip_args: Vec<String> = if template == "web-dev" {
                vec![
                    "exec".into(),
                    "-w".into(),
                    work_dir.into(),
                    container_name.clone(),
                    "npm".into(),
                    "install".into(),
                ]
            } else {
                vec![
                    "exec".into(),
                    "-w".into(),
                    work_dir.into(),
                    container_name.clone(),
                    "python".into(),
                    "-m".into(),
                    "pip".into(),
                    "install".into(),
                    "-v".into(),
                    "--progress-bar".into(),
                    "on".into(),
                    "-r".into(),
                    "requirements.txt".into(),
                ]
            };
            let pip_refs: Vec<&str> = pip_args.iter().map(String::as_str).collect();
            run_docker_exec_logged(&app, &pip_refs).await?;
        }

        if run_r {
            let _ = app.emit(
                "project-install-log",
                "Installing R packages from install.R...",
            );
            let work = work_dir.trim_end_matches('/');
            let r_expr = format!(
                "options(repos=c(CRAN='{CRAN_MIRROR}')); source('{work}/install.R')"
            );
            let r_args = [
                "exec".to_string(),
                "-w".into(),
                work_dir.into(),
                container_name.clone(),
                "Rscript".into(),
                "-e".into(),
                r_expr,
            ];
            let r_refs: Vec<&str> = r_args.iter().map(String::as_str).collect();
            run_docker_exec_logged(&app, &r_refs).await?;
        }

        Ok((
            "Dependencies installed successfully".to_string(),
            "".to_string(),
        ))
    };

    let install_timeout_secs = if run_pip && run_r { 900 } else { 300 };
    match tokio::time::timeout(std::time::Duration::from_secs(install_timeout_secs), fut).await {
        Ok(Ok((stdout, _))) => json!({ "ok": true, "log": stdout }),
        Ok(Err(e)) => json!({ "ok": false, "error": e }),
        Err(_) => json!({ "ok": false, "error": "Timeout installing dependencies" }),
    }
}

pub fn scaffold_mobile_react_native(
    project_dir: &std::path::Path,
    env_vars: &[(&str, &str)],
) -> Result<(), String> {
    let w = |path: &str, content: &str| {
        std::fs::write(project_dir.join(path), content)
            .map_err(|e| format!("[SCAFFOLD_FAILED] write {path}: {e}"))
    };
    std::fs::create_dir_all(project_dir.join("android"))
        .map_err(|e| format!("[SCAFFOLD_FAILED] mkdir android: {e}"))?;
    std::fs::create_dir_all(project_dir.join("ios"))
        .map_err(|e| format!("[SCAFFOLD_FAILED] mkdir ios: {e}"))?;

    let package_json = serde_json::json!({
        "name": "lumina-mobile-app",
        "version": "0.0.1",
        "private": true,
        "scripts": {
            "android": "react-native run-android",
            "ios": "react-native run-ios",
            "start": "react-native start",
            "test": "jest"
        },
        "dependencies": {
            "react": "18.2.0",
            "react-native": "0.74.0",
            "@react-navigation/native": "^6.1.0",
            "@react-navigation/stack": "^6.3.0"
        },
        "devDependencies": {
            "@babel/core": "^7.20.0",
            "@babel/preset-env": "^7.20.0",
            "@babel/runtime": "^7.20.0",
            "@react-native/metro-config": "^0.74.0",
            "@types/react": "^18.0.24",
            "@types/react-native": "^0.72.0",
            "jest": "^29.0.0",
            "typescript": "5.0.4"
        },
        "jest": {
            "preset": "react-native"
        }
    });
    w(
        "package.json",
        &serde_json::to_string_pretty(&package_json).unwrap(),
    )?;

    w(
        "metro.config.js",
        r#"const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const config = {};
module.exports = mergeConfig(getDefaultConfig(__dirname), config);
"#,
    )?;

    w(
        "index.js",
        r#"import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './package.json';
AppRegistry.registerComponent(appName, () => App);
"#,
    )?;

    w(
        "App.tsx",
        r#"import React from 'react';
import {SafeAreaView, Text, StyleSheet} from 'react-native';

export default function App(): React.JSX.Element {
  return (
    <SafeAreaView style={styles.container}>
      <Text style={styles.title}>LuminaDev Mobile App</Text>
      <Text style={styles.subtitle}>Edit App.tsx to get started.</Text>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#1a1a2e'},
  title: {fontSize: 24, fontWeight: 'bold', color: '#e0e0ff'},
  subtitle: {fontSize: 14, color: '#9090aa', marginTop: 8},
});
"#,
    )?;

    let mut env_content = String::new();
    for (k, v) in env_vars {
        env_content.push_str(&format!("{k}={v}\n"));
    }
    w(".env", &env_content)?;

    w(
        ".gitignore",
        "node_modules/\n.env\nbuild/\nandroid/app/build/\nios/build/\n*.jks\n*.keystore\n",
    )?;

    let appium_port = find_free_port(4723);
    let json_server_port = find_free_port(3001);
    w(
        "docker-compose.yml",
        &format!(
            r#"services:
  appium:
    image: appium/appium:latest
    ports:
      - "{appium_port}:4723"
    environment:
      - ANDROID_SDK_ROOT=/opt/android-sdk
  json-server:
    image: clue/json-server
    ports:
      - "{json_server_port}:80"
    volumes:
      - ./mock-data.json:/data/db.json
"#
        ),
    )?;

    w(
        "mock-data.json",
        r#"{"users": [], "posts": []}
"#,
    )?;

    w(
        "tsconfig.json",
        r#"{
  "extends": "@react-native/typescript-config/tsconfig.json"
}
"#,
    )?;

    Ok(())
}

pub fn scaffold_mobile_flutter(
    project_dir: &std::path::Path,
    env_vars: &[(&str, &str)],
) -> Result<(), String> {
    let w = |path: &str, content: &str| {
        if let Some(parent) = std::path::Path::new(path).parent() {
            let _ = std::fs::create_dir_all(project_dir.join(parent));
        }
        std::fs::write(project_dir.join(path), content)
            .map_err(|e| format!("[SCAFFOLD_FAILED] write {path}: {e}"))
    };

    w(
        "pubspec.yaml",
        r#"name: lumina_mobile_app
description: LuminaDev Flutter project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.0
  go_router: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
"#,
    )?;

    w(
        "lib/main.dart",
        r#"import 'package:flutter/material.dart';

void main() {
  runApp(const LuminaApp());
}

class LuminaApp extends StatelessWidget {
  const LuminaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'LuminaDev Flutter App',
      theme: ThemeData(colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple)),
      home: const Scaffold(
        body: Center(
          child: Text('LuminaDev Flutter App', style: TextStyle(fontSize: 24)),
        ),
      ),
    );
  }
}
"#,
    )?;

    w(
        "test/widget_test.dart",
        r#"import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:lumina_mobile_app/main.dart';

void main() {
  testWidgets('App smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(const LuminaApp());
    expect(find.text('LuminaDev Flutter App'), findsOneWidget);
  });
}
"#,
    )?;

    let mut env_content = String::new();
    for (k, v) in env_vars {
        env_content.push_str(&format!("{k}={v}\n"));
    }
    w(".env", &env_content)?;

    w(
        ".gitignore",
        ".dart_tool/\n.flutter-plugins\n.flutter-plugins-dependencies\nbuild/\n.env\n",
    )?;

    w(
        "docker-compose.yml",
        r#"services:
  flutter-dev:
    image: cirrusci/flutter:stable
    working_dir: /app
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: flutter pub get
    environment:
      - DISPLAY=${DISPLAY}
"#,
    )?;

    w(
        "analysis_options.yaml",
        r#"include: package:flutter_lints/flutter.yaml
"#,
    )?;

    Ok(())
}

pub fn scaffold_ai_ml(
    project_dir: &std::path::Path,
    env_vars: &[(&str, &str)],
) -> Result<(), String> {
    let w = |path: &str, content: &str| {
        if let Some(parent) = std::path::Path::new(path).parent() {
            let _ = std::fs::create_dir_all(project_dir.join(parent));
        }
        std::fs::write(project_dir.join(path), content)
            .map_err(|e| format!("[SCAFFOLD_FAILED] write {path}: {e}"))
    };

    let _ = std::fs::create_dir_all(project_dir.join("data"));
    w("data/.gitkeep", "")?;

    w(
        "requirements.txt",
        r#"# Core ML
torch>=2.2.0
torchvision>=0.17.0
transformers>=4.40.0
datasets>=2.19.0
accelerate>=0.29.0

# LLM / Agents
langchain>=0.2.0
langchain-community>=0.2.0
langchain-ollama>=0.1.0
llama-index>=0.10.0
openai>=1.30.0

# Jupyter
jupyter>=1.0.0
ipykernel>=6.29.0
jupyterlab>=4.2.0

# Utilities
python-dotenv>=1.0.0
pandas>=2.2.0
numpy>=1.26.0
matplotlib>=3.8.0
scikit-learn>=1.4.0
ollama>=0.2.0
"#,
    )?;

    w(
        "setup.sh",
        r#"#!/usr/bin/env bash
set -e
echo "Setting up AI/ML environment..."
python -m venv .venv
. .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
if command -v ollama &> /dev/null && curl -sf http://localhost:11434 > /dev/null 2>&1; then
  echo "Pulling llama3 model (this may take a few minutes)..."
  ollama pull llama3
else
  echo "Warning: Ollama not running. Run 'ollama pull llama3' manually after starting Ollama."
fi
echo "Setup complete. Activate with: source .venv/bin/activate"
"#,
    )?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(
            project_dir.join("setup.sh"),
            std::fs::Permissions::from_mode(0o755),
        );
    }

    w(
        "Modelfile",
        r#"FROM llama3
SYSTEM """
You are a senior software engineer and AI/ML assistant embedded in a local development environment.
Help with code, debugging, model selection, and technical explanations.
Be concise and accurate. When showing code, use the correct language and best practices.
"""
PARAMETER temperature 0.7
PARAMETER num_ctx 4096
"#,
    )?;

    let notebook = r##"{
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.11.0"}
 },
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["# LuminaDev AI/ML Starter\n\nPre-configured with LangChain, Ollama, and Transformers."]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import transformers\n",
    "import langchain\n",
    "import ollama\n",
    "print('torch:', torch.__version__)\n",
    "print('transformers:', transformers.__version__)\n",
    "print('langchain:', langchain.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from langchain_ollama import OllamaLLM\n",
    "llm = OllamaLLM(model='llama3', base_url='http://localhost:11434')\n",
    "response = llm.invoke('Explain gradient descent in 2 sentences.')\n",
    "print(response)"
   ]
  }
 ]
}"##;
    w("notebooks/starter.ipynb", notebook)?;

    w("src/__init__.py", "")?;

    w(
        "src/pipeline.py",
        r#""""LangChain pipeline wired to local Ollama LLM."""
from langchain_ollama import OllamaLLM
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
import os

OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
MODEL = os.getenv("OLLAMA_MODEL", "llama3")


def build_chain(template: str = "{question}") -> LLMChain:
    llm = OllamaLLM(model=MODEL, base_url=OLLAMA_HOST)
    prompt = PromptTemplate(input_variables=["question"], template=template)
    return LLMChain(llm=llm, prompt=prompt)


if __name__ == "__main__":
    chain = build_chain()
    result = chain.invoke({"question": "What is a transformer model?"})
    print(result["text"])
"#,
    )?;

    let mut env_lines =
        "OLLAMA_HOST=http://localhost:11434\nOLLAMA_MODEL=llama3\nJUPYTER_PORT=8888\n".to_string();
    for (k, v) in env_vars {
        env_lines.push_str(&format!("{k}={v}\n"));
    }
    w(".env", &env_lines)?;

    w(
        ".gitignore",
        ".venv/\ndata/\n__pycache__/\n*.pyc\n.ipynb_checkpoints/\n.env\n*.egg-info/\n",
    )?;

    w("README.md", "# AI/ML Project\n\nGenerated by LuminaDev.\n\n## Quick Start\n\n```bash\nbash setup.sh\nsource .venv/bin/activate\njupyter lab\n```\n")?;

    let ollama_port = find_free_port(11434);
    let jupyter_port = find_free_port(8888);
    w(
        "docker-compose.yml",
        &format!(
            r#"services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "{ollama_port}:11434"
    volumes:
      - ollama_data:/root/.ollama
  jupyter:
    image: jupyter/scipy-notebook:latest
    ports:
      - "{jupyter_port}:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
volumes:
  ollama_data:
"#
        ),
    )?;

    Ok(())
}

pub fn scaffold_docs(project_dir: &std::path::Path) -> Result<(), String> {
    let w = |path: &str, content: &str| {
        if let Some(parent) = std::path::Path::new(path).parent() {
            let _ = std::fs::create_dir_all(project_dir.join(parent));
        }
        std::fs::write(project_dir.join(path), content)
            .map_err(|e| format!("[SCAFFOLD_FAILED] write {path}: {e}"))
    };

    let project_name = project_dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("Lumina Documentation");

    w(
        "mkdocs.yml",
        &format!(
            r#"site_name: {project_name}
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
"#
        ),
    )?;

    w(
        "docs/index.md",
        &format!(
            r#"# Welcome to {project_name}

This project was scaffolded with a professional MkDocs Material environment.

## Getting Started

- Edit `docs/index.md` to update this home page.
- Add more markdown files to `docs/` and link them in `mkdocs.yml`.
"#
        ),
    )?;

    Ok(())
}

pub fn detect_template(project_dir: &std::path::Path) -> String {
    if project_dir.join("package.json").exists() {
        "web-dev".to_string()
    } else {
        "data-science".to_string()
    }
}

pub fn scaffold_editor_configs(project_dir: &std::path::Path, template: &str, editor_cmd: &str) {
    // 1. VS Code / Cursor: Always write/ensure .vscode/extensions.json
    let vscode_dir = project_dir.join(".vscode");
    let _ = std::fs::create_dir_all(&vscode_dir);
    let vscode_content = if template == "data-science" {
        r#"{
  "recommendations": [
    "ms-python.python",
    "ms-toolsai.jupyter"
  ]
}"#
    } else {
        r#"{
  "recommendations": [
    "dbaeumer.vscode-eslint",
    "esbenp.prettier-vscode",
    "ms-vscode.vscode-typescript-next"
  ]
}"#
    };
    let _ = std::fs::write(vscode_dir.join("extensions.json"), vscode_content);

    // 2. IntelliJ IDEA: If the editor cmd is idea or webstorm or eclipse
    if editor_cmd.contains("idea")
        || editor_cmd.contains("webstorm")
        || editor_cmd.contains("eclipse")
    {
        let idea_dir = project_dir.join(".idea");
        let _ = std::fs::create_dir_all(&idea_dir);

        let modules_content = r#"<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ProjectModuleManager">
    <modules>
      <module fileurl="file://$PROJECT_DIR$/.idea/project.iml" filepath="$PROJECT_DIR$/.idea/project.iml" />
    </modules>
  </component>
</project>"#;
        let _ = std::fs::write(idea_dir.join("modules.xml"), modules_content);

        let iml_content = if template == "data-science" {
            r#"<?xml version="1.0" encoding="UTF-8"?>
<module type="PYTHON_MODULE" version="4">
  <component name="NewModuleRootManager">
    <content url="file://$MODULE_DIR$/.." />
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>"#
        } else {
            r#"<?xml version="1.0" encoding="UTF-8"?>
<module type="WEB_MODULE" version="4">
  <component name="NewModuleRootManager">
    <content url="file://$MODULE_DIR$/.." />
    <orderEntry type="inheritedJdk" />
    <orderEntry type="sourceFolder" forTests="false" />
  </component>
</module>"#
        };
        let _ = std::fs::write(idea_dir.join("project.iml"), iml_content);

        if template == "data-science" {
            let misc_content = r#"<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="ProjectRootManager" version="2" project-jdk-name="Python 3" project-jdk-type="Python SDK" />
</project>"#;
            let _ = std::fs::write(idea_dir.join("misc.xml"), misc_content);
        }
    }

    // 3. Neovim / Pyright
    if template == "data-science" {
        let pyright_content = r#"{
  "include": ["src", "tests", "main.py"],
  "exclude": ["**/node_modules", "**/__pycache__"]
}"#;
        let _ = std::fs::write(project_dir.join("pyrightconfig.json"), pyright_content);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    #[test]
    fn test_scaffold_editor_configs_vscode_data_science() {
        let base_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("test_scaffold_vscode_ds");
        let _ = std::fs::remove_dir_all(&base_dir);
        let _ = std::fs::create_dir_all(&base_dir);

        scaffold_editor_configs(&base_dir, "data-science", "code");

        let ext_file = base_dir.join(".vscode").join("extensions.json");
        assert!(ext_file.exists());

        let content = std::fs::read_to_string(ext_file).unwrap();
        assert!(content.contains("ms-python.python"));
        assert!(content.contains("ms-toolsai.jupyter"));

        let pyright_file = base_dir.join("pyrightconfig.json");
        assert!(pyright_file.exists());

        let _ = std::fs::remove_dir_all(&base_dir);
    }

    #[test]
    fn test_scaffold_editor_configs_intellij_web_dev() {
        let base_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("test_scaffold_idea_web");
        let _ = std::fs::remove_dir_all(&base_dir);
        let _ = std::fs::create_dir_all(&base_dir);

        scaffold_editor_configs(&base_dir, "web-dev", "idea");

        let ext_file = base_dir.join(".vscode").join("extensions.json");
        assert!(ext_file.exists());

        let content = std::fs::read_to_string(ext_file).unwrap();
        assert!(content.contains("esbenp.prettier-vscode"));

        let idea_modules = base_dir.join(".idea").join("modules.xml");
        let idea_iml = base_dir.join(".idea").join("project.iml");
        assert!(idea_modules.exists());
        assert!(idea_iml.exists());

        let iml_content = std::fs::read_to_string(idea_iml).unwrap();
        assert!(iml_content.contains("WEB_MODULE"));

        let _ = std::fs::remove_dir_all(&base_dir);
    }

    #[test]
    fn scaffold_rn_creates_expected_files() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_mobile_react_native(dir.path(), &[]).unwrap();
        assert!(dir.path().join("package.json").exists());
        assert!(dir.path().join("metro.config.js").exists());
        assert!(dir.path().join("index.js").exists());
        assert!(dir.path().join("App.tsx").exists());
        assert!(dir.path().join(".env").exists());
        assert!(dir.path().join(".gitignore").exists());
        assert!(dir.path().join("android").is_dir());
        assert!(dir.path().join("ios").is_dir());
    }

    #[test]
    fn scaffold_flutter_creates_expected_files() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_mobile_flutter(dir.path(), &[]).unwrap();
        assert!(dir.path().join("pubspec.yaml").exists());
        assert!(dir.path().join("lib/main.dart").exists());
        assert!(dir.path().join("test/widget_test.dart").exists());
        assert!(dir.path().join(".env").exists());
        assert!(dir.path().join("docker-compose.yml").exists());
    }

    #[test]
    fn test_detect_template() {
        let base_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("target")
            .join("test_detect_template");
        let _ = std::fs::remove_dir_all(&base_dir);
        let _ = std::fs::create_dir_all(&base_dir);

        assert_eq!(detect_template(&base_dir), "data-science");

        let _ = std::fs::write(base_dir.join("package.json"), "{}");
        assert_eq!(detect_template(&base_dir), "web-dev");

        let _ = std::fs::remove_dir_all(&base_dir);
    }

    #[test]
    fn scaffold_ai_ml_creates_expected_files() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_ai_ml(dir.path(), &[]).unwrap();
        assert!(dir.path().join("requirements.txt").exists());
        assert!(dir.path().join("setup.sh").exists());
        assert!(dir.path().join("notebooks/starter.ipynb").exists());
        assert!(dir.path().join("src/__init__.py").exists());
        assert!(dir.path().join("src/pipeline.py").exists());
        assert!(dir.path().join("data/.gitkeep").exists());
        assert!(dir.path().join(".env").exists());
        assert!(dir.path().join("Modelfile").exists());
        assert!(dir.path().join("docker-compose.yml").exists());

        let reqs = std::fs::read_to_string(dir.path().join("requirements.txt")).unwrap();
        assert!(reqs.contains("torch"));
        assert!(reqs.contains("langchain"));
    }

    #[tokio::test]
    async fn handle_scaffold_mobile_rn_dispatches() {
        let dir = tempfile::TempDir::new().unwrap();
        let body = serde_json::json!({
            "path": dir.path().to_str().unwrap(),
            "template": "mobile",
            "subTemplate": "react-native"
        });
        let result = handle_project_scaffold(body).await;
        assert_eq!(result["ok"], true);
        assert!(dir.path().join("package.json").exists());
    }

    #[tokio::test]
    async fn handle_scaffold_mobile_flutter_dispatches() {
        let dir = tempfile::TempDir::new().unwrap();
        let body = serde_json::json!({
            "path": dir.path().to_str().unwrap(),
            "template": "mobile",
            "subTemplate": "flutter"
        });
        let result = handle_project_scaffold(body).await;
        assert_eq!(result["ok"], true);
        assert!(dir.path().join("pubspec.yaml").exists());
    }

    #[tokio::test]
    async fn handle_scaffold_ai_ml_dispatches() {
        let dir = tempfile::TempDir::new().unwrap();
        let body = serde_json::json!({
            "path": dir.path().to_str().unwrap(),
            "template": "ai-ml"
        });
        let result = handle_project_scaffold(body).await;
        assert_eq!(result["ok"], true);
        assert!(dir.path().join("requirements.txt").exists());
    }

    #[tokio::test]
    async fn handle_scaffold_missing_path_returns_error() {
        let result = handle_project_scaffold(serde_json::json!({
            "template": "web-dev"
        }))
        .await;
        assert_eq!(result["ok"], false);
        assert!(result["error"]
            .as_str()
            .unwrap_or("")
            .contains("[SCAFFOLD_FAILED]"));
        assert!(result["error"]
            .as_str()
            .unwrap_or("")
            .contains("Missing path"));
    }

    #[tokio::test]
    async fn handle_scaffold_empty_template_creates_dir_only() {
        let dir = tempfile::TempDir::new().unwrap();
        let result = handle_project_scaffold(serde_json::json!({
            "path": dir.path().to_str().unwrap(),
            "template": ""
        }))
        .await;
        assert_eq!(result["ok"], true);
        assert!(dir.path().exists());
    }

    #[tokio::test]
    async fn handle_scaffold_unknown_template_creates_dir_only() {
        let dir = tempfile::TempDir::new().unwrap();
        let result = handle_project_scaffold(serde_json::json!({
            "path": dir.path().to_str().unwrap(),
            "template": "nonexistent-template"
        }))
        .await;
        assert_eq!(result["ok"], true);
        assert!(dir.path().exists());
    }

    #[tokio::test]
    async fn handle_scaffold_data_science_creates_full_structure() {
        let dir = tempfile::TempDir::new().unwrap();
        let result = handle_project_scaffold(serde_json::json!({
            "path": dir.path().to_str().unwrap(),
            "template": "data-science",
            "options": {
                "dependencies": { "pandas": "latest", "numpy": "1.26.0" },
                "createMainScript": true,
                "createNotebook": true
            }
        }))
        .await;
        assert_eq!(
            result["ok"],
            true,
            "data-science scaffold failed: {:?}",
            result.get("error")
        );

        assert!(dir.path().join("data/raw/.gitkeep").exists());
        assert!(dir.path().join("data/processed/.gitkeep").exists());
        assert!(dir.path().join("src/__init__.py").exists());
        assert!(dir.path().join("src/db.py").exists());
        assert!(dir.path().join("src/data_loader.py").exists());
        assert!(dir.path().join("tests/test_db.py").exists());
        assert!(dir.path().join(".env").exists());
        assert!(dir.path().join(".gitignore").exists());
        assert!(dir.path().join("README.md").exists());
        assert!(dir.path().join("main.py").exists());
        assert!(dir.path().join("notebooks/01_exploration.ipynb").exists());

        let reqs = std::fs::read_to_string(dir.path().join("requirements.txt")).unwrap();
        assert!(reqs.contains("pandas"), "expected pandas in requirements");
        assert!(
            reqs.contains("numpy==1.26.0"),
            "expected numpy==1.26.0 in requirements"
        );

        let vscode = dir.path().join(".vscode").join("extensions.json");
        assert!(vscode.exists());
        let vscode_content = std::fs::read_to_string(vscode).unwrap();
        assert!(vscode_content.contains("ms-python.python"));

        let pyright = dir.path().join("pyrightconfig.json");
        assert!(pyright.exists());
    }

    #[tokio::test]
    async fn handle_scaffold_data_science_r_toolchain() {
        let dir = tempfile::TempDir::new().unwrap();
        let result = handle_project_scaffold(serde_json::json!({
            "path": dir.path().to_str().unwrap(),
            "template": "data-science",
            "options": {
                "toolchain": "r",
                "dependencies": { "tidyverse": "latest" },
                "createMainScript": true,
                "createNotebook": true
            }
        }))
        .await;
        assert_eq!(
            result["ok"],
            true,
            "R scaffold failed: {:?}",
            result.get("error")
        );

        // Directories always created
        assert!(dir.path().join("data/raw/.gitkeep").exists());
        assert!(dir.path().join("data/processed/.gitkeep").exists());

        // R files exist
        assert!(dir.path().join("src/db.R").exists());
        assert!(dir.path().join("src/data_loader.R").exists());
        assert!(dir.path().join("main.R").exists());
        assert!(dir.path().join("install.R").exists());
        assert!(dir.path().join("notebooks/01_exploration.ipynb").exists());

        // Python files should NOT exist
        assert!(!dir.path().join("src/__init__.py").exists());
        assert!(!dir.path().join("src/db.py").exists());
        assert!(!dir.path().join("src/data_loader.py").exists());
        assert!(!dir.path().join("tests/test_db.py").exists());
        assert!(!dir.path().join("main.py").exists());
        assert!(!dir.path().join("requirements.txt").exists());

        let install_r = std::fs::read_to_string(dir.path().join("install.R")).unwrap();
        assert!(install_r.contains("tidyverse"));
        assert!(install_r.contains("cloud.r-project.org"));

        // VS Code extensions include R support
        let vscode = dir.path().join(".vscode").join("extensions.json");
        assert!(vscode.exists());
        let vscode_content = std::fs::read_to_string(vscode).unwrap();
        assert!(
            vscode_content.contains("reditorsupport.r"),
            "expected R extension in vscode"
        );
    }

    #[tokio::test]
    async fn handle_scaffold_data_science_both_toolchain() {
        let dir = tempfile::TempDir::new().unwrap();
        let result = handle_project_scaffold(serde_json::json!({
            "path": dir.path().to_str().unwrap(),
            "template": "data-science",
            "options": {
                "toolchain": "both",
                "dependencies": { "pandas": "latest" },
                "rDependencies": { "tidyverse": "latest" },
                "createMainScript": true,
                "createNotebook": true
            }
        }))
        .await;
        assert_eq!(
            result["ok"],
            true,
            "both scaffold failed: {:?}",
            result.get("error")
        );

        // Python files exist
        assert!(dir.path().join("src/__init__.py").exists());
        assert!(dir.path().join("src/db.py").exists());
        assert!(dir.path().join("src/data_loader.py").exists());
        assert!(dir.path().join("main.py").exists());
        assert!(dir.path().join("requirements.txt").exists());
        let reqs = std::fs::read_to_string(dir.path().join("requirements.txt")).unwrap();
        assert!(reqs.contains("pandas"));
        assert!(!reqs.contains("tidyverse"));
        let install_r = std::fs::read_to_string(dir.path().join("install.R")).unwrap();
        assert!(install_r.contains("tidyverse"));
        assert!(install_r.contains("cloud.r-project.org"));

        // R files also exist
        assert!(dir.path().join("src/db.R").exists());
        assert!(dir.path().join("src/data_loader.R").exists());
        assert!(dir.path().join("main.R").exists());
        assert!(dir.path().join("install.R").exists());

        // Both notebooks exist
        assert!(dir.path().join("notebooks/01_exploration.ipynb").exists());
        assert!(dir.path().join("notebooks/02_exploration_r.ipynb").exists());

        // VS Code extensions include R support
        let vscode = dir.path().join(".vscode").join("extensions.json");
        assert!(vscode.exists());
        let vscode_content = std::fs::read_to_string(vscode).unwrap();
        assert!(
            vscode_content.contains("reditorsupport.r"),
            "expected R extension in vscode for both"
        );
    }

    #[tokio::test]
    async fn handle_scaffold_web_dev_creates_full_structure() {
        let dir = tempfile::TempDir::new().unwrap();
        let result = handle_project_scaffold(serde_json::json!({
            "path": dir.path().to_str().unwrap(),
            "template": "web-dev",
            "options": {
                "dependencies": { "axios": "^1.6.0" }
            }
        }))
        .await;
        assert_eq!(
            result["ok"],
            true,
            "web-dev scaffold failed: {:?}",
            result.get("error")
        );

        assert!(dir.path().join("src/components/.gitkeep").exists());
        assert!(dir.path().join("src/pages/.gitkeep").exists());
        assert!(dir.path().join("public/.gitkeep").exists());
        assert!(dir.path().join("src/main.tsx").exists());
        assert!(dir.path().join("index.html").exists());
        assert!(dir.path().join("vite.config.ts").exists());
        assert!(dir.path().join(".env").exists());
        assert!(dir.path().join(".gitignore").exists());
        assert!(dir.path().join("README.md").exists());

        let pkg = std::fs::read_to_string(dir.path().join("package.json")).unwrap();
        assert!(pkg.contains("react"));
        assert!(pkg.contains("vite"));
        assert!(pkg.contains("axios"), "expected axios in dependencies");

        let vscode = dir.path().join(".vscode").join("extensions.json");
        assert!(vscode.exists());
        let vscode_content = std::fs::read_to_string(vscode).unwrap();
        assert!(vscode_content.contains("dbaeumer.vscode-eslint"));
    }

    #[test]
    fn deps_install_plan_r_toolchain_skips_pip() {
        let dir = tempfile::TempDir::new().unwrap();
        std::fs::write(dir.path().join("install.R"), "install.packages(\"tidyverse\")\n").unwrap();
        let plan = deps_install_plan("data-science", "r", "My Lab", dir.path()).unwrap();
        assert_eq!(plan.container_name, "my-lab-jupyter-1");
        assert!(!plan.run_pip);
        assert!(plan.run_r);
    }

    #[test]
    fn deps_install_plan_python_toolchain_uses_pip() {
        let dir = tempfile::TempDir::new().unwrap();
        std::fs::write(dir.path().join("requirements.txt"), "pandas\n").unwrap();
        let plan = deps_install_plan("data-science", "python", "lab", dir.path()).unwrap();
        assert!(plan.run_pip);
        assert!(!plan.run_r);
    }

    #[test]
    fn deps_install_plan_both_toolchain_runs_pip_and_r() {
        let dir = tempfile::TempDir::new().unwrap();
        std::fs::write(dir.path().join("requirements.txt"), "pandas\n").unwrap();
        std::fs::write(dir.path().join("install.R"), "install.packages(\"ggplot2\")\n").unwrap();
        let plan = deps_install_plan("data-science", "both", "lab", dir.path()).unwrap();
        assert!(plan.run_pip);
        assert!(plan.run_r);
    }

    #[test]
    fn scaffold_editor_configs_no_intellij_when_not_requested() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_editor_configs(dir.path(), "web-dev", "code");
        let idea_dir = dir.path().join(".idea");
        assert!(
            !idea_dir.exists(),
            "should not create .idea when editor is 'code'"
        );
    }

    #[test]
    fn scaffold_editor_configs_webstorm_triggers_intellij() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_editor_configs(dir.path(), "web-dev", "webstorm");
        assert!(dir.path().join(".idea/modules.xml").exists());
        assert!(dir.path().join(".idea/project.iml").exists());

        let iml = std::fs::read_to_string(dir.path().join(".idea/project.iml")).unwrap();
        assert!(iml.contains("WEB_MODULE"));
    }

    #[test]
    fn scaffold_editor_configs_eclipse_triggers_intellij_data_science() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_editor_configs(dir.path(), "data-science", "eclipse");
        assert!(dir.path().join(".idea/modules.xml").exists());
        let iml = std::fs::read_to_string(dir.path().join(".idea/project.iml")).unwrap();
        assert!(iml.contains("PYTHON_MODULE"));
        assert!(dir.path().join(".idea/misc.xml").exists());
    }

    #[test]
    fn detect_template_returns_data_science_by_default() {
        let dir = tempfile::TempDir::new().unwrap();
        assert_eq!(detect_template(dir.path()), "data-science");
    }

    #[test]
    fn find_free_port_returns_preferred_when_available() {
        let port = find_free_port(43210);
        assert!(port >= 43210);
        assert!(port < 43210 + 200);
    }

    #[test]
    fn scaffold_editor_configs_empty_editor_skips_intellij() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_editor_configs(dir.path(), "data-science", "");
        assert!(dir.path().join(".vscode/extensions.json").exists());
        let idea_dir = dir.path().join(".idea");
        assert!(
            !idea_dir.exists(),
            "should not create .idea when editor_cmd is empty"
        );
        assert!(dir.path().join("pyrightconfig.json").exists());
    }

    #[tokio::test]
    async fn handle_scaffold_home_dir_fallback_returns_error() {
        let result = handle_project_scaffold(serde_json::json!({
            "path": "",
            "template": "web-dev"
        }))
        .await;
        assert_eq!(result["ok"], false);
        assert!(result["error"]
            .as_str()
            .unwrap_or("")
            .contains("Missing path"));
    }

    #[test]
    fn scaffold_ai_ml_sets_executable_permission_on_setup_sh() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_ai_ml(dir.path(), &[]).unwrap();
        let setup = dir.path().join("setup.sh");
        assert!(setup.exists());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let meta = std::fs::metadata(&setup).unwrap();
            assert!(
                meta.permissions().mode() & 0o111 != 0,
                "setup.sh should be executable"
            );
        }
    }

    #[test]
    fn scaffold_mobile_react_native_includes_tsconfig() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_mobile_react_native(dir.path(), &[]).unwrap();
        assert!(dir.path().join("tsconfig.json").exists());
        let tsconfig = std::fs::read_to_string(dir.path().join("tsconfig.json")).unwrap();
        assert!(tsconfig.contains("react-native"));
    }

    #[test]
    fn scaffold_flutter_docker_compose_has_expected_content() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_mobile_flutter(dir.path(), &[("DISPLAY", ":0")]).unwrap();
        let dc = std::fs::read_to_string(dir.path().join("docker-compose.yml")).unwrap();
        assert!(dc.contains("cirrusci/flutter"));
        assert!(dc.contains("DISPLAY"));
    }

    #[test]
    fn scaffold_docs_creates_expected_files() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_docs(dir.path()).unwrap();
        assert!(dir.path().join("mkdocs.yml").exists());
        assert!(dir.path().join("docs/index.md").exists());

        // Assert site name matches directory name dynamically
        let mkdocs_content = std::fs::read_to_string(dir.path().join("mkdocs.yml")).unwrap();
        assert!(mkdocs_content.contains("site_name:"));
    }

    #[test]
    fn render_install_r_script_sets_cran_mirror() {
        let script = render_install_r_script(&["ggplot2".to_string(), "dplyr".to_string()]);
        assert!(script.contains("cloud.r-project.org"));
        assert!(script.contains("\"ggplot2\""));
        assert!(script.contains("install.packages(pkgs"));
    }
}
