use crate::project_scaffold::ports::find_free_port;

pub(crate) fn scaffold_ai_ml(
    project_dir: &std::path::Path,
    env_vars: &[(&str, &str)],
) -> Result<(), String> {
    let w = |path: &str, content: &str| {
        if let Some(parent) = std::path::Path::new(path).parent() {
            let _ = std::fs::create_dir_all(project_dir.join(parent));
        }
        std::fs::write(project_dir.join(path), content)
            .map_err(|e| format!("[SCAFFOLD_FAILED] write {path}: {e}"))
    };

    let _ = std::fs::create_dir_all(project_dir.join("data"));
    w("data/.gitkeep", "")?;

    w(
        "requirements.txt",
        r#"# Core ML
torch>=2.2.0
torchvision>=0.17.0
transformers>=4.40.0
datasets>=2.19.0
accelerate>=0.29.0

# LLM / Agents
langchain>=0.2.0
langchain-community>=0.2.0
langchain-ollama>=0.1.0
llama-index>=0.10.0
openai>=1.30.0

# Jupyter
jupyter>=1.0.0
ipykernel>=6.29.0
jupyterlab>=4.2.0

# Utilities
python-dotenv>=1.0.0
pandas>=2.2.0
numpy>=1.26.0
matplotlib>=3.8.0
scikit-learn>=1.4.0
ollama>=0.2.0
"#,
    )?;

    w(
        "setup.sh",
        r#"#!/usr/bin/env bash
set -e
echo "Setting up AI/ML environment..."
python -m venv .venv
. .venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
if command -v ollama &> /dev/null && curl -sf http://localhost:11434 > /dev/null 2>&1; then
  echo "Pulling llama3 model (this may take a few minutes)..."
  ollama pull llama3
else
  echo "Warning: Ollama not running. Run 'ollama pull llama3' manually after starting Ollama."
fi
echo "Setup complete. Activate with: source .venv/bin/activate"
"#,
    )?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(
            project_dir.join("setup.sh"),
            std::fs::Permissions::from_mode(0o755),
        );
    }

    w(
        "Modelfile",
        r#"FROM llama3
SYSTEM """
You are a senior software engineer and AI/ML assistant embedded in a local development environment.
Help with code, debugging, model selection, and technical explanations.
Be concise and accurate. When showing code, use the correct language and best practices.
"""
PARAMETER temperature 0.7
PARAMETER num_ctx 4096
"#,
    )?;

    let notebook = r##"{
 "nbformat": 4,
 "nbformat_minor": 5,
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.11.0"}
 },
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": ["# LuminaDev AI/ML Starter\n\nPre-configured with LangChain, Ollama, and Transformers."]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import transformers\n",
    "import langchain\n",
    "import ollama\n",
    "print('torch:', torch.__version__)\n",
    "print('transformers:', transformers.__version__)\n",
    "print('langchain:', langchain.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from langchain_ollama import OllamaLLM\n",
    "llm = OllamaLLM(model='llama3', base_url='http://localhost:11434')\n",
    "response = llm.invoke('Explain gradient descent in 2 sentences.')\n",
    "print(response)"
   ]
  }
 ]
}"##;
    w("notebooks/starter.ipynb", notebook)?;

    w("src/__init__.py", "")?;

    w(
        "src/pipeline.py",
        r#""""LangChain pipeline wired to local Ollama LLM."""
from langchain_ollama import OllamaLLM
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain
import os

OLLAMA_HOST = os.getenv("OLLAMA_HOST", "http://localhost:11434")
MODEL = os.getenv("OLLAMA_MODEL", "llama3")


def build_chain(template: str = "{question}") -> LLMChain:
    llm = OllamaLLM(model=MODEL, base_url=OLLAMA_HOST)
    prompt = PromptTemplate(input_variables=["question"], template=template)
    return LLMChain(llm=llm, prompt=prompt)


if __name__ == "__main__":
    chain = build_chain()
    result = chain.invoke({"question": "What is a transformer model?"})
    print(result["text"])
"#,
    )?;

    let mut env_lines =
        "OLLAMA_HOST=http://localhost:11434\nOLLAMA_MODEL=llama3\nJUPYTER_PORT=8888\n".to_string();
    for (k, v) in env_vars {
        env_lines.push_str(&format!("{k}={v}\n"));
    }
    w(".env", &env_lines)?;

    w(
        ".gitignore",
        ".venv/\ndata/\n__pycache__/\n*.pyc\n.ipynb_checkpoints/\n.env\n*.egg-info/\n",
    )?;

    w("README.md", "# AI/ML Project\n\nGenerated by LuminaDev.\n\n## Quick Start\n\n```bash\nbash setup.sh\nsource .venv/bin/activate\njupyter lab\n```\n")?;

    let ollama_port = find_free_port(11434);
    let jupyter_port = find_free_port(8888);
    w(
        "docker-compose.yml",
        &format!(
            r#"services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "{ollama_port}:11434"
    volumes:
      - ollama_data:/root/.ollama
  jupyter:
    image: jupyter/scipy-notebook:latest
    ports:
      - "{jupyter_port}:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
volumes:
  ollama_data:
"#
        ),
    )?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scaffold_ai_ml_creates_expected_files() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_ai_ml(dir.path(), &[]).unwrap();
        assert!(dir.path().join("requirements.txt").exists());
        assert!(dir.path().join("setup.sh").exists());
        assert!(dir.path().join("notebooks/starter.ipynb").exists());
        assert!(dir.path().join("src/__init__.py").exists());
        assert!(dir.path().join("src/pipeline.py").exists());
        assert!(dir.path().join("data/.gitkeep").exists());
        assert!(dir.path().join(".env").exists());
        assert!(dir.path().join("Modelfile").exists());
        assert!(dir.path().join("docker-compose.yml").exists());

        let reqs = std::fs::read_to_string(dir.path().join("requirements.txt")).unwrap();
        assert!(reqs.contains("torch"));
        assert!(reqs.contains("langchain"));
    }

    #[test]
    fn scaffold_ai_ml_sets_executable_permission_on_setup_sh() {
        let dir = tempfile::TempDir::new().unwrap();
        scaffold_ai_ml(dir.path(), &[]).unwrap();
        let setup = dir.path().join("setup.sh");
        assert!(setup.exists());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let meta = std::fs::metadata(&setup).unwrap();
            assert!(
                meta.permissions().mode() & 0o111 != 0,
                "setup.sh should be executable"
            );
        }
    }
}
