/// Data-science project template scaffold.
/// Supports Python, R, or both toolchains.
pub(crate) fn scaffold_data_science(
    project_dir: &std::path::Path,
    options: &serde_json::Value,
) -> Result<(), String> {
    let toolchain = options
        .get("toolchain")
        .and_then(|v| v.as_str())
        .unwrap_or("python");
    let create_python = toolchain == "python" || toolchain == "both";
    let create_r = toolchain == "r" || toolchain == "both";

    // Create professional directories
    let _ = std::fs::create_dir_all(project_dir.join("data/raw"));
    let _ = std::fs::create_dir_all(project_dir.join("data/processed"));
    let _ = std::fs::create_dir_all(project_dir.join("notebooks"));
    let _ = std::fs::create_dir_all(project_dir.join("src"));
    let _ = std::fs::create_dir_all(project_dir.join("tests"));

    let _ = std::fs::write(project_dir.join("data/raw/.gitkeep"), "");
    let _ = std::fs::write(project_dir.join("data/processed/.gitkeep"), "");
    if create_python {
        let _ = std::fs::write(project_dir.join("src/__init__.py"), "");
    }

    // Generate .env
    let env_content = "DATABASE_URL=postgresql://postgres:luminadev@postgres:5432/datasci\n";
    let _ = std::fs::write(project_dir.join(".env"), env_content);

    // Generate .gitignore
    let mut gitignore = String::from(".env\ndata/raw/*\n!data/raw/.gitkeep\ndata/processed/*\n!data/processed/.gitkeep\n.ipynb_checkpoints/\n");
    if create_python {
        gitignore.push_str("__pycache__/\n*.pyc\n");
    }
    if create_r {
        gitignore.push_str(".Rhistory\n.RData\n.Ruserdata\n");
    }
    let _ = std::fs::write(project_dir.join(".gitignore"), gitignore);

    // Generate README.md
    let readme = "# Data Science Project\n\nGenerated by LuminaDev.\n\n## Structure\n- `data/`: Raw and processed datasets.\n- `notebooks/`: Jupyter notebooks.\n- `src/`: Reusable modules.\n- `tests/`: Unit tests.\n".to_string();
    let _ = std::fs::write(project_dir.join("README.md"), readme);

    if create_python {
        scaffold_data_science_python(project_dir, options);
    }

    if create_r {
        scaffold_data_science_r(project_dir, options, create_python);
    }

    let create_main = options
        .get("createMainScript")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);
    if create_main {
        if create_python {
            let main_content = r#"from src.db import get_engine

def main():
    try:
        engine = get_engine()
        with engine.connect() as conn:
            print("Successfully connected to the database!")
    except Exception as e:
        print(f"Error connecting to database: {e}")

if __name__ == '__main__':
    main()
"#;
            let _ = std::fs::write(project_dir.join("main.py"), main_content);
        }

        if create_r {
            let main_r = r#"source("src/db.R")

main <- function() {
  tryCatch({
    con <- get_engine()
    print("Successfully connected to the database!")
  }, error = function(e) {
    print(paste("Error connecting to database:", e$message))
  })
}

if (!interactive()) {
  main()
}
"#;
            let _ = std::fs::write(project_dir.join("main.R"), main_r);
        }
    }

    let create_notebook = options
        .get("createNotebook")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);
    if create_notebook {
        if create_python {
            let notebook_content = r##"{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data Exploration\n",
    "Welcome to your LuminaDev Data Science project."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from src.db import get_engine\n",
    "import pandas as pd\n",
    "\n",
    "engine = get_engine()\n",
    "print('Database connected!')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}"##;
            let _ = std::fs::write(
                project_dir.join("notebooks/01_exploration.ipynb"),
                notebook_content,
            );
        }

        if create_r {
            let notebook_r = r##"{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# R Data Exploration\n",
    "Welcome to your LuminaDev Data Science project (R)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "source('src/db.R')\n",
    "print('Database connected!')"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "R",
   "language": "R",
   "name": "ir"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}"##;
            let name = if create_python {
                "notebooks/02_exploration_r.ipynb"
            } else {
                "notebooks/01_exploration.ipynb"
            };
            let _ = std::fs::write(project_dir.join(name), notebook_r);
        }
    }

    crate::project_scaffold::editor_configs::scaffold_editor_configs(
        project_dir,
        "data-science",
        "",
    );
    if create_r {
        let extensions_json = r#"{
  "recommendations": [
    "ms-python.python",
    "ms-toolsai.jupyter",
    "reditorsupport.r"
  ]
}"#;
        let _ = std::fs::write(project_dir.join(".vscode/extensions.json"), extensions_json);
    }
    Ok(())
}

fn scaffold_data_science_python(project_dir: &std::path::Path, options: &serde_json::Value) {
    // Generate src/db.py
    let db_py = r#"import os
from sqlalchemy import create_engine

def get_engine():
    db_url = os.environ.get('DATABASE_URL')
    if not db_url:
        raise ValueError("DATABASE_URL environment variable is not set")
    return create_engine(db_url)
"#;
    let _ = std::fs::write(project_dir.join("src/db.py"), db_py);

    // Generate tests/test_db.py
    let test_db_py = r#"import unittest

class TestDatabase(unittest.TestCase):
    def test_connection_string(self):
        # Placeholder test
        self.assertTrue(True)

if __name__ == '__main__':
    unittest.main()
"#;
    let _ = std::fs::write(project_dir.join("tests/test_db.py"), test_db_py);

    // Generate src/data_loader.py
    let data_loader = r#"import pandas as pd
from .db import get_engine

def load_data_from_db(query: str) -> pd.DataFrame:
    engine = get_engine()
    return pd.read_sql(query, engine)
"#;
    let _ = std::fs::write(project_dir.join("src/data_loader.py"), data_loader);

    // Generate requirements.txt
    let deps = options
        .get("dependencies")
        .and_then(|v| v.as_object())
        .filter(|o| !o.is_empty())
        .cloned()
        .unwrap_or_default();
    let mut reqs = String::new();
    for (name, version) in deps.iter() {
        let v_str = version.as_str().unwrap_or("latest").trim();
        if v_str.is_empty() || v_str == "latest" {
            reqs.push_str(name);
        } else {
            reqs.push_str(&format!("{}=={}", name, v_str));
        }
        reqs.push('\n');
    }
    let _ = std::fs::write(project_dir.join("requirements.txt"), reqs);
}

fn scaffold_data_science_r(
    project_dir: &std::path::Path,
    options: &serde_json::Value,
    create_python: bool,
) {
    let db_r = r#"library(DBI)
library(RPostgres)

get_engine <- function() {
  db_url <- Sys.getenv("DATABASE_URL")
  if (db_url == "") stop("DATABASE_URL environment variable is not set")

  # Placeholder connection logic
  # dbConnect(RPostgres::Postgres(), ...)
}
"#;
    let _ = std::fs::write(project_dir.join("src/db.R"), db_r);

    let data_loader_r = r#"source("src/db.R")

load_data_from_db <- function(query) {
  # Placeholder
}
"#;
    let _ = std::fs::write(project_dir.join("src/data_loader.R"), data_loader_r);

    // Generate install.R
    let deps = options
        .get("rDependencies")
        .and_then(|v| v.as_object())
        .filter(|o| !o.is_empty())
        .cloned()
        .or_else(|| {
            options
                .get("dependencies")
                .and_then(|v| v.as_object())
                .cloned()
        })
        .unwrap_or_default();
    let r_names: Vec<String> = deps.keys().map(|k| k.to_string()).collect();
    let _ = std::fs::write(
        project_dir.join("install.R"),
        crate::project_scaffold::r_packages::render_install_r_script(&r_names),
    );

    let _ = create_python; // suppress unused warning when R-only
}
