pub(crate) fn scaffold_web_dev(
    project_dir: &std::path::Path,
    options: &serde_json::Value,
) -> Result<(), String> {
    use serde_json::json;

    // Create professional directories
    let _ = std::fs::create_dir_all(project_dir.join("src/components"));
    let _ = std::fs::create_dir_all(project_dir.join("src/pages"));
    let _ = std::fs::create_dir_all(project_dir.join("public"));

    let _ = std::fs::write(project_dir.join("src/components/.gitkeep"), "");
    let _ = std::fs::write(project_dir.join("src/pages/.gitkeep"), "");
    let _ = std::fs::write(project_dir.join("public/.gitkeep"), "");

    // Generate .env
    let env_content = "DATABASE_URL=postgresql://postgres:luminadev@postgres:5432/webapp\n";
    let _ = std::fs::write(project_dir.join(".env"), env_content);

    // Generate .gitignore
    let gitignore = "node_modules\n.env\ndist\nbuild\n.DS_Store\n";
    let _ = std::fs::write(project_dir.join(".gitignore"), gitignore);

    // Generate README.md
    let readme = "# Web Development Project\n\nGenerated by LuminaDev.\n".to_string();
    let _ = std::fs::write(project_dir.join("README.md"), readme);

    let mut deps = options
        .get("dependencies")
        .and_then(|v| v.as_object())
        .cloned()
        .unwrap_or_default();
    deps.insert("react".to_string(), json!("^18.3.1"));
    deps.insert("react-dom".to_string(), json!("^18.3.1"));

    let mut dev_deps = options
        .get("devDependencies")
        .and_then(|v| v.as_object())
        .cloned()
        .unwrap_or_default();
    dev_deps.insert("vite".to_string(), json!("^5.4.1"));
    dev_deps.insert("typescript".to_string(), json!("^5.5.3"));
    dev_deps.insert("@vitejs/plugin-react".to_string(), json!("^4.3.1"));
    dev_deps.insert("@types/react".to_string(), json!("^18.3.3"));
    dev_deps.insert("@types/react-dom".to_string(), json!("^18.3.0"));

    // Generate package.json
    let package_json = serde_json::json!({
      "name": "lumina-web-app",
      "version": "1.0.0",
      "private": true,
      "scripts": {
         "dev": "vite",
         "build": "tsc && vite build",
         "preview": "vite preview"
      },
      "dependencies": deps,
      "devDependencies": dev_deps
    });

    let _ = std::fs::write(
        project_dir.join("package.json"),
        serde_json::to_string_pretty(&package_json).unwrap(),
    );

    // Generate index.html and src/main.tsx
    let index_html = r#"<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LuminaDev Web App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>"#;
    let _ = std::fs::write(project_dir.join("index.html"), index_html);

    let main_tsx = r#"import React from 'react'
import ReactDOM from 'react-dom/client'

const App = () => {
  return (
    <div style={{ padding: 40, fontFamily: 'sans-serif' }}>
      <h1>Welcome to LuminaDev Web App!</h1>
      <p>This project was scaffolded with a professional Dockerized architecture.</p>
    </div>
  )
}

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
"#;
    let _ = std::fs::write(project_dir.join("src/main.tsx"), main_tsx);

    let vite_config = r#"import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    host: '0.0.0.0', // needed for Docker
    port: 5173
  }
})
"#;
    let _ = std::fs::write(project_dir.join("vite.config.ts"), vite_config);

    crate::project_scaffold::editor_configs::scaffold_editor_configs(project_dir, "web-dev", "");
    Ok(())
}
