import { z } from 'zod'

import { JobCancelRequestSchema, JobStartRequestSchema, SessionInfoRequestSchema } from './foundation.js'
import { IPC } from './ipc.js'
import {
  CloudAuthConnectPatRequestSchema,
  CloudAuthConnectPollRequestSchema,
  CloudAuthConnectStartRequestSchema,
  CloudAuthDisconnectRequestSchema,
  CloudGitCreatePrRequestSchema,
  CloudGitFindPrRequestSchema,
  CloudGitGetPrChecksRequestSchema,
  CloudGitInboxRequestSchema,
  CloudGitIssuesRequestSchema,
  CloudGitMergePrRequestSchema,
  CloudGitPipelinesRequestSchema,
  CloudGitPrsRequestSchema,
  CloudGitReleasesRequestSchema,
  CloudGitReviewRequestsRequestSchema,
  ComposeDownRequestSchema,
  ComposeLogsRequestSchema,
  ComposeStopRequestSchema,
  ComposeUpRequestSchema,
  DiagnosticsBundleCreateRequestSchema,
  DockerActionRequestSchema,
  DockerCleanupRunRequestSchema,
  DockerContainerStatsRequestSchema,
  DockerCreateRequestSchema,
  DockerGetTagsRequestSchema,
  DockerImageActionRequestSchema,
  DockerInspectRequestSchema,
  DockerInstallRequestSchema,
  DockerLogsRequestSchema,
  DockerNetworkActionRequestSchema,
  DockerNetworkCreateRequestSchema,
  DockerPullRequestSchema,
  DockerReconfigureRequestSchema,
  DockerRemapPortRequestSchema,
  DockerSearchRequestSchema,
  DockerTerminalRequestSchema,
  DockerVolumeActionRequestSchema,
  DockerVolumeCreateRequestSchema,
  EditorOpenRequestSchema,
  EmptyRequestSchema,
  FsExistsRequestSchema,
  FsOpenRequestSchema,
  GitCloneRequestSchema,
  GitConfigListRequestSchema,
  GitConfigSetKeyRequestSchema,
  GitConfigSetRequestSchema,
  GitRecentAddRequestSchema,
  GitStatusRequestSchema,
  GitVcsBranchesRequestSchema,
  GitVcsCheckoutRequestSchema,
  GitVcsCommitRequestSchema,
  GitVcsConflictDiffRequestSchema,
  GitVcsConflictHunksRequestSchema,
  GitVcsDiffRequestSchema,
  GitVcsFetchRequestSchema,
  GitVcsMergeAbortRequestSchema,
  GitVcsMergeContinueRequestSchema,
  GitVcsMergeRequestSchema,
  GitVcsPullRequestSchema,
  GitVcsPushRequestSchema,
  GitVcsRebaseAbortRequestSchema,
  GitVcsRebaseContinueRequestSchema,
  GitVcsRebaseRequestSchema,
  GitVcsRebaseSkipRequestSchema,
  GitVcsRemotesRequestSchema,
  GitVcsRenameBranchRequestSchema,
  GitVcsResolveConflictRequestSchema,
  GitVcsResolveHunkRequestSchema,
  GitVcsStageRequestSchema,
  GitVcsStashPopRequestSchema,
  GitVcsStashRequestSchema,
  GitVcsStatusRequestSchema,
  GitVcsUnstageRequestSchema,
  HostExecRequestSchema,
  LogStreamStartRequestSchema,
  LogStreamStopRequestSchema,
  PortsSuggestRequestSchema,
  ProfileCredentialsGetRequestSchema,
  ProfileCredentialsIdRequestSchema,
  ProfileCredentialsStoreRequestSchema,
  ProfileRunningStatusRequestSchema,
  ProfileSwitchRequestSchema,
  ProjectEnsureDirRequestSchema,
  ProjectInstallDepsRequestSchema,
  ProjectScaffoldRequestSchema,
  RuntimeCheckDepsRequestSchema,
  RuntimeGetVersionsRequestSchema,
  RuntimeInstalledVersionsRequestSchema,
  RuntimeRemoveVersionRequestSchema,
  RuntimeSetActiveRequestSchema,
  RuntimeUninstallPreviewRequestSchema,
  SshGenerateRequestSchema,
  SshGetPubRequestSchema,
  SshListDirRequestSchema,
  SshSetupRemoteKeyRequestSchema,
  SshTestGithubRequestSchema,
  StoreDeleteRequestSchema,
  StoreGetRequestSchema,
  StoreSetRequestSchema,
  SystemReadinessFixRequestSchema,
  TerminalCloseRequestSchema,
  TerminalCreateRequestSchema,
  TerminalResizeRequestSchema,
  TerminalWriteRequestSchema,
} from './schemas.js'

type IpcChannel = (typeof IPC)[keyof typeof IPC]

/** Dialog plugin APIs and terminal event streams — not validated at ipc_invoke / ipc_send boundary. */
export const IPC_CHANNELS_EXCLUDED_FROM_SCHEMA: ReadonlySet<IpcChannel> = new Set([
  IPC.selectFolder,
  IPC.filePickOpen,
  IPC.filePickSave,
  IPC.terminalData,
  IPC.terminalExit,
])

const NO_PAYLOAD: readonly IpcChannel[] = [
  IPC.dockerList,
  IPC.dockerImagesList,
  IPC.dockerVolumesList,
  IPC.dockerNetworksList,
  IPC.dockerPrune,
  IPC.dockerPrunePreview,
  IPC.metrics,
  IPC.profileCredentialsList,
  IPC.openExternalTerminal,
  IPC.editorList,
  IPC.gitRecentList,
  IPC.gitDoctorScan,
  IPC.sshEnableLocal,
  IPC.appInfo,
  IPC.jobsList,
  IPC.dockerCheckInstalled,
  IPC.getHostDistro,
  IPC.getHostPorts,
  IPC.getHostSysInfo,
  IPC.monitorTopProcesses,
  IPC.monitorSecurity,
  IPC.monitorSecurityDrilldown,
  IPC.runtimeStatus,
  IPC.perfSnapshot,
  IPC.systemReadinessCheck,
  IPC.terminalGetAllEnv,
  IPC.cloudAuthStatus,
  IPC.appUpdateCheck,
]

const PAYLOAD: ReadonlyArray<readonly [IpcChannel, z.ZodTypeAny]> = [
  [IPC.dockerAction, DockerActionRequestSchema],
  [IPC.dockerLogs, DockerLogsRequestSchema],
  [IPC.dockerCreate, DockerCreateRequestSchema],
  [IPC.dockerPull, DockerPullRequestSchema],
  [IPC.dockerRemapPort, DockerRemapPortRequestSchema],
  [IPC.dockerInspect, DockerInspectRequestSchema],
  [IPC.dockerReconfigure, DockerReconfigureRequestSchema],
  [IPC.dockerContainerStats, DockerContainerStatsRequestSchema],
  [IPC.dockerImageAction, DockerImageActionRequestSchema],
  [IPC.dockerVolumeAction, DockerVolumeActionRequestSchema],
  [IPC.dockerVolumeCreate, DockerVolumeCreateRequestSchema],
  [IPC.dockerNetworkAction, DockerNetworkActionRequestSchema],
  [IPC.dockerNetworkCreate, DockerNetworkCreateRequestSchema],
  [IPC.dockerCleanupRun, DockerCleanupRunRequestSchema],
  [IPC.dockerInstall, DockerInstallRequestSchema],
  [IPC.dockerSearch, DockerSearchRequestSchema],
  [IPC.dockerGetTags, DockerGetTagsRequestSchema],
  [IPC.dockerTerminal, DockerTerminalRequestSchema],
  [IPC.hostExec, HostExecRequestSchema],
  [IPC.composeUp, ComposeUpRequestSchema],
  [IPC.composeLogs, ComposeLogsRequestSchema],
  [IPC.composeDown, ComposeDownRequestSchema],
  [IPC.composeStop, ComposeStopRequestSchema],
  [IPC.profileSwitch, ProfileSwitchRequestSchema],
  [IPC.profileCredentialsStore, ProfileCredentialsStoreRequestSchema],
  [IPC.profileCredentialsDelete, ProfileCredentialsIdRequestSchema],
  [IPC.profileCredentialsGet, ProfileCredentialsGetRequestSchema],
  [IPC.profileRunningStatus, ProfileRunningStatusRequestSchema],
  [IPC.terminalCreate, TerminalCreateRequestSchema],
  [IPC.terminalWrite, TerminalWriteRequestSchema],
  [IPC.terminalResize, TerminalResizeRequestSchema],
  [IPC.terminalClose, TerminalCloseRequestSchema],
  [IPC.editorOpen, EditorOpenRequestSchema],
  [IPC.gitClone, GitCloneRequestSchema],
  [IPC.gitStatus, GitStatusRequestSchema],
  [IPC.gitRecentAdd, GitRecentAddRequestSchema],
  [IPC.gitConfigSet, GitConfigSetRequestSchema],
  [IPC.gitConfigSetKey, GitConfigSetKeyRequestSchema],
  [IPC.gitConfigList, GitConfigListRequestSchema],
  [IPC.sshGenerate, SshGenerateRequestSchema],
  [IPC.sshGetPub, SshGetPubRequestSchema],
  [IPC.sshTestGithub, SshTestGithubRequestSchema],
  [IPC.sshListDir, SshListDirRequestSchema],
  [IPC.sshSetupRemoteKey, SshSetupRemoteKeyRequestSchema],
  [IPC.storeGet, StoreGetRequestSchema],
  [IPC.storeSet, StoreSetRequestSchema],
  [IPC.storeDelete, StoreDeleteRequestSchema],
  [IPC.sessionInfo, SessionInfoRequestSchema],
  [IPC.jobStart, JobStartRequestSchema],
  [IPC.jobCancel, JobCancelRequestSchema],
  [IPC.logStreamStart, LogStreamStartRequestSchema],
  [IPC.logStreamStop, LogStreamStopRequestSchema],
  [IPC.runtimeInstalledVersions, RuntimeInstalledVersionsRequestSchema],
  [IPC.runtimeGetVersions, RuntimeGetVersionsRequestSchema],
  [IPC.runtimeSetActive, RuntimeSetActiveRequestSchema],
  [IPC.runtimeCheckDeps, RuntimeCheckDepsRequestSchema],
  [IPC.runtimeUninstallPreview, RuntimeUninstallPreviewRequestSchema],
  [IPC.runtimeRemoveVersion, RuntimeRemoveVersionRequestSchema],
  [IPC.diagnosticsBundleCreate, DiagnosticsBundleCreateRequestSchema],
  [IPC.systemReadinessFix, SystemReadinessFixRequestSchema],
  [IPC.cloudAuthConnectStart, CloudAuthConnectStartRequestSchema],
  [IPC.cloudAuthConnectPoll, CloudAuthConnectPollRequestSchema],
  [IPC.cloudAuthConnectPat, CloudAuthConnectPatRequestSchema],
  [IPC.cloudAuthDisconnect, CloudAuthDisconnectRequestSchema],
  [IPC.cloudGitPrs, CloudGitPrsRequestSchema],
  [IPC.cloudGitReviewRequests, CloudGitReviewRequestsRequestSchema],
  [IPC.cloudGitInbox, CloudGitInboxRequestSchema],
  [IPC.cloudGitPipelines, CloudGitPipelinesRequestSchema],
  [IPC.cloudGitIssues, CloudGitIssuesRequestSchema],
  [IPC.cloudGitReleases, CloudGitReleasesRequestSchema],
  [IPC.cloudGitCreatePr, CloudGitCreatePrRequestSchema],
  [IPC.cloudGitFindPr, CloudGitFindPrRequestSchema],
  [IPC.cloudGitGetPrChecks, CloudGitGetPrChecksRequestSchema],
  [IPC.cloudGitMergePr, CloudGitMergePrRequestSchema],
  [IPC.gitVcsStatus, GitVcsStatusRequestSchema],
  [IPC.gitVcsRemotes, GitVcsRemotesRequestSchema],
  [IPC.gitVcsDiff, GitVcsDiffRequestSchema],
  [IPC.gitVcsStage, GitVcsStageRequestSchema],
  [IPC.gitVcsUnstage, GitVcsUnstageRequestSchema],
  [IPC.gitVcsCommit, GitVcsCommitRequestSchema],
  [IPC.gitVcsPush, GitVcsPushRequestSchema],
  [IPC.gitVcsPull, GitVcsPullRequestSchema],
  [IPC.gitVcsFetch, GitVcsFetchRequestSchema],
  [IPC.gitVcsBranches, GitVcsBranchesRequestSchema],
  [IPC.gitVcsCheckout, GitVcsCheckoutRequestSchema],
  [IPC.gitVcsStash, GitVcsStashRequestSchema],
  [IPC.gitVcsMerge, GitVcsMergeRequestSchema],
  [IPC.gitVcsRebase, GitVcsRebaseRequestSchema],
  [IPC.gitVcsStashPop, GitVcsStashPopRequestSchema],
  [IPC.gitVcsMergeAbort, GitVcsMergeAbortRequestSchema],
  [IPC.gitVcsRebaseAbort, GitVcsRebaseAbortRequestSchema],
  [IPC.gitVcsMergeContinue, GitVcsMergeContinueRequestSchema],
  [IPC.gitVcsRebaseContinue, GitVcsRebaseContinueRequestSchema],
  [IPC.gitVcsRebaseSkip, GitVcsRebaseSkipRequestSchema],
  [IPC.gitVcsRenameBranch, GitVcsRenameBranchRequestSchema],
  [IPC.gitVcsConflictDiff, GitVcsConflictDiffRequestSchema],
  [IPC.gitVcsConflictHunks, GitVcsConflictHunksRequestSchema],
  [IPC.gitVcsResolveConflict, GitVcsResolveConflictRequestSchema],
  [IPC.gitVcsResolveHunk, GitVcsResolveHunkRequestSchema],
  [IPC.portsSuggest, PortsSuggestRequestSchema],
  [IPC.projectEnsureDir, ProjectEnsureDirRequestSchema],
  [IPC.projectScaffold, ProjectScaffoldRequestSchema],
  [IPC.projectInstallDeps, ProjectInstallDepsRequestSchema],
  [IPC.fsExists, FsExistsRequestSchema],
  [IPC.fsOpen, FsOpenRequestSchema],
]

/** Payload (channel, schema) pairs — exported for source/dist drift guard tests. */
export const IPC_PAYLOAD_CHANNEL_SCHEMAS: ReadonlyArray<readonly [IpcChannel, z.ZodTypeAny]> =
  PAYLOAD

function buildIpcRequestSchemas(): Record<IpcChannel, z.ZodTypeAny> {
  const map = {} as Record<IpcChannel, z.ZodTypeAny>
  for (const channel of NO_PAYLOAD) {
    map[channel] = EmptyRequestSchema
  }
  for (const [channel, schema] of PAYLOAD) {
    map[channel] = schema
  }
  return map
}

/** Canonical channel → Zod request schema for ipc_invoke and ipc_send payloads. */
export const IPC_REQUEST_SCHEMAS: Record<IpcChannel, z.ZodTypeAny> = buildIpcRequestSchemas()

export type IpcSchemaCoverageStats = {
  totalIpcChannels: number
  dispatcherChannels: number
  excludedFromMap: number
  mappedChannels: number
  payloadChannels: number
  noPayloadChannels: number
  unmappedDispatcherChannels: string[]
}

export function ipcSchemaCoverageStats(): IpcSchemaCoverageStats {
  const all = Object.values(IPC)
  const excluded = IPC_CHANNELS_EXCLUDED_FROM_SCHEMA
  const dispatcher = all.filter((c) => !excluded.has(c))
  const mapped = dispatcher.filter((c) => c in IPC_REQUEST_SCHEMAS)
  const noPayload = mapped.filter((c) => IPC_REQUEST_SCHEMAS[c] === EmptyRequestSchema)
  const payloadChannels = mapped.length - noPayload.length
  const unmapped = dispatcher.filter((c) => !(c in IPC_REQUEST_SCHEMAS))

  return {
    totalIpcChannels: all.length,
    dispatcherChannels: dispatcher.length,
    excludedFromMap: excluded.size,
    mappedChannels: mapped.length,
    payloadChannels,
    noPayloadChannels: noPayload.length,
    unmappedDispatcherChannels: unmapped,
  }
}
